export const ItemType = {
  Ammunition: 'Ammunition',
  Amulet: 'Amulet',
  Axe: 'Axe',
  BodyArmor: 'BodyArmor',
  Essence: 'Essence',
  Gem: 'Gem',
  Helm: 'Helm',
  Javelin: 'Javelin',
  Potion: 'Potion',
  Ring: 'Ring',
  Rune: 'Rune',
  Scroll: 'Scroll',
  Shield: 'Shield',
  Spear: 'Spear',
  Sword: 'Sword',
  Token: 'Token',
  Tome: 'Tome',
};
