export const RecipeType = {
  Amulet: 'Amulet',
  Gem: 'Gem',
  Event: 'Event',
  Potion: 'Potion',
  Quest: 'Quest',
  Magic: 'Magic',
  Rare: 'Rare',
  RepairRecharge: 'Repair/Recharge',
  Ring: 'Ring',
  Rune: 'Rune',
  Socket: 'Socket',
  Stack: 'Stack',
  Upgrade: 'Upgrade',
};
