/**
 * @readonly
 * @enum {string}
 */
export const ItemType = {
  Ammunition: 'Ammunition',
  Amulet: 'Amulet',
  AssassinKatar: 'AssassinKatar',
  Axe: 'Axe',
  BarbarianHelm: 'BarbarianHelm',
  Belt: 'Belt',
  BodyArmor: 'BodyArmor',
  Boot: 'Boot',
  Bow: 'Bow',
  Charm: 'Charm',
  Circlet: 'Circlet',
  Crossbow: 'Crossbow',
  Dagger: 'Dagger',
  Essence: 'Essence',
  Gem: 'Gem',
  Glove: 'Glove',
  Helm: 'Helm',
  Javelin: 'Javelin',
  Jewel: 'Jewel',
  Key: 'Key',
  Quest: 'Quest',
  Mace: 'Mace',
  Organ: 'Organ',
  Polearm: 'Polearm',
  Potion: 'Potion',
  Ring: 'Ring',
  Rune: 'Rune',
  Scepter: 'Scepter',
  Scroll: 'Scroll',
  Shield: 'Shield',
  Spear: 'Spear',
  Staff: 'Staff',
  Sword: 'Sword',
  Token: 'Token',
  Tome: 'Tome',
  Wand: 'Wand',
};
