export const RunewordType = {
  AmnElIthTirSol: 'AmnElIthTirSol',
  AmnRalThul: 'AmnRalThul',
  AmnTir: 'AmnTir',
  DolEldHelIstTirVex: 'DolEldHelIstTirVex',
  EthRalOrtTal: 'EthRalOrtTal',
  HelLumFal: 'HelLumFal',
  IthElEth: 'IthElEth',
  JahGulEth: 'JahGulEth',
  JahIthBer: 'JahIthBer',
  LumIoSolEth: 'LumIoSolEth',
  NefLum: 'NefLum',
  NefTir: 'NefTir',
  NefSolIth: 'NefSolIth',
  OrtSol: 'OrtSol',
  RalOrtTal: 'RalOrtTal',
  ShaelEth: 'ShaelEth',
  ShaelKoNef: 'ShaelKoNef',
  TalEth: 'TalEth',
  TalThulOrtAmn: 'TalThulOrtAmn',
  ThulIoNef: 'ThulIoNef',
  TirEl: 'TirEl',
  TirRal: 'TirRal',
};
