/**
 * @readonly
 * @enum {string}
 */
export const SkillType = {
  Attract: 'Attract',
  BattleCommand: 'BattleCommand',
  BattleCry: 'BattleCry',
  BattleOrders: 'BattleOrders',
  BoneArmor: 'BoneArmor',
  BoneSpear: 'BoneSpear',
  ChainLightning: 'ChainLightning',
  ChargedBolt: 'ChargedBolt',
  CloakOfShadows: 'CloakOfShadows',
  ColdMastery: 'ColdMastery',
  Confuse: 'Confuse',
  CorpseExplosion: 'CorpseExplosion',
  CriticalStrike: 'CriticalStrike',
  Delirium: 'Delirium',
  Dodge: 'Dodge',
  Enchant: 'Enchant',
  EnergyShield: 'EnergyShield',
  Fanaticism: 'Fanaticism',
  FireBall: 'FireBall',
  FireBolt: 'FireBolt',
  FireMastery: 'FireMastery',
  FireWall: 'FireWall',
  Frenzy: 'Frenzy',
  FrostNova: 'FrostNova',
  FrozenOrb: 'FrozenOrb',
  GlacialSpike: 'GlacialSpike',
  HolyBolt: 'HolyBolt',
  HolyShock: 'HolyShock',
  IceBlast: 'IceBlast',
  Inferno: 'Inferno',
  LightningMastery: 'LightningMastery',
  Lycanthropy: 'Lycanthropy',
  Meteor: 'Meteor',
  MindBlast: 'MindBlast',
  Nova: 'Nova',
  PoisonExplosion: 'PoisonExplosion',
  PoisonNova: 'PoisonNova',
  SkeletonMastery: 'SkeletonMastery',
  SlowMissles: 'SlowMissles',
  SpiritOfBarbs: 'SpiritOfBarbs',
  SpiritWolf: 'SpiritWolf',
  StaticField: 'StaticField',
  SummonGrizzly: 'SummonGrizzly',
  Teleport: 'Teleport',
  Terror: 'Terror',
  Thorns: 'Thorns',
  Twister: 'Twister',
  Warmth: 'Warmth',
  Weaken: 'Weaken',
  Werebear: 'Werebear',
  Whirlwind: 'Whirlwind',
};
