import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  PlayerClassType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  playerClass: PlayerClassType.Amazon,
  type: ItemType.AmazonWeapon,
})([
  {
    id: ids.StagBow,
    name: 'Stag Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Normal,
    size: [4, 2],
    clvl: 14,
    qlvl: 18,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [7, 12],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [30],
        [BasePropertyType.MinimumDexterity]: [45],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.ReflexBow,
    name: 'Reflex Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Normal,
    size: [4, 2],
    clvl: 20,
    qlvl: 27,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [9, 19],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [35],
        [BasePropertyType.MinimumDexterity]: [60],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.MaidenSpear,
    name: 'Maiden Spear',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Normal,
    size: [4, 2],
    clvl: 14,
    qlvl: 18,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [18, 24],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [54],
        [BasePropertyType.MinimumDexterity]: [40],
        [BasePropertyType.Durability]: [28],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.MaidenPike,
    name: 'Maiden Pike',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Normal,
    size: [4, 2],
    clvl: 20,
    qlvl: 27,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [23, 55],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [63],
        [BasePropertyType.MinimumDexterity]: [52],
        [BasePropertyType.Durability]: [25],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.MaidenJavelin,
    name: 'Maiden Javelin',
    class: WeaponClassType.Javelin,
    tier: ItemTierType.Normal,
    size: [3, 1],
    clvl: 17,
    qlvl: 23,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [8, 14],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [33],
        [BasePropertyType.MinimumDexterity]: [47],
      },
    },
  },
  {
    id: ids.AshwoodBow,
    name: 'Ashwood Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    clvl: 29,
    qlvl: 39,
    baseId: ids.StagBow,
    imageId: ids.StagBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [16, 29],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [56],
        [BasePropertyType.MinimumDexterity]: [77],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.CeremonialBow,
    name: 'Ceremonial Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    clvl: 35,
    qlvl: 47,
    baseId: ids.ReflexBow,
    imageId: ids.ReflexBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [19, 41],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [73],
        [BasePropertyType.MinimumDexterity]: [110],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.CeremonialSpear,
    name: 'Ceremonial Spear',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    clvl: 14,
    qlvl: 18,
    baseId: ids.MaidenSpear,
    imageId: ids.MaidenSpear,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [34, 51],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [101],
        [BasePropertyType.MinimumDexterity]: [80],
        [BasePropertyType.Durability]: [28],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.CeremonialPike,
    name: 'Ceremonial Pike',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    clvl: 38,
    qlvl: 51,
    baseId: ids.MaidenPike,
    imageId: ids.MaidenPike,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [42, 101],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [20],
        [BasePropertyType.MinimumStrength]: [115],
        [BasePropertyType.MinimumDexterity]: [98],
        [BasePropertyType.Durability]: [25],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.CeremonialJavelin,
    name: 'Ceremonial Javelin',
    class: WeaponClassType.Javelin,
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    clvl: 26,
    qlvl: 35,
    baseId: ids.MaidenJavelin,
    imageId: ids.MaidenJavelin,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [18, 35],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.MinimumDexterity]: [109],
      },
    },
  },
  {
    id: ids.MatriarchalBow,
    name: 'Matriarchal Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Elite,
    size: [4, 2],
    clvl: 39,
    qlvl: 53,
    baseId: ids.StagBow,
    imageId: ids.StagBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [20, 47],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [87],
        [BasePropertyType.MinimumDexterity]: [187],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.GrandMatronBow,
    name: 'Grand Matron Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Elite,
    size: [4, 2],
    clvl: 58,
    qlvl: 78,
    baseId: ids.ReflexBow,
    imageId: ids.ReflexBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [14, 72],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [108],
        [BasePropertyType.MinimumDexterity]: [152],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.MatriarchalSpear,
    name: 'Matriarchal Spear',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Elite,
    size: [4, 2],
    clvl: 45,
    qlvl: 61,
    baseId: ids.MaidenSpear,
    imageId: ids.MaidenSpear,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [65, 95],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [114],
        [BasePropertyType.MinimumDexterity]: [142],
        [BasePropertyType.Durability]: [28],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.MatriarchalPike,
    name: 'Matriarchal Pike',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Elite,
    size: [4, 2],
    clvl: 60,
    qlvl: 81,
    baseId: ids.MaidenPike,
    imageId: ids.MaidenPike,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [37, 153],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [20],
        [BasePropertyType.MinimumStrength]: [132],
        [BasePropertyType.MinimumDexterity]: [149],
        [BasePropertyType.Durability]: [25],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.MatriarchalJavelin,
    name: 'Matriarchal Javelin',
    class: WeaponClassType.Javelin,
    tier: ItemTierType.Elite,
    size: [3, 1],
    clvl: 48,
    qlvl: 65,
    baseId: ids.MaidenJavelin,
    imageId: ids.MaidenJavelin,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [30, 54],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [107],
        [BasePropertyType.MinimumDexterity]: [151],
      },
    },
  },
]);
