import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  PlayerClassType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  playerClass: PlayerClassType.Amazon,
  type: ItemType.AmazonWeapon,
})([
  {
    id: ids.StagBow,
    name: 'Stag Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 7, y: 12},
        [BasePropertyType.RequiredDexterity]: 45,
        [BasePropertyType.RequiredStrength]: 30,
        [BasePropertyType.RequiredLevel]: 14,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.ReflexBow,
    name: 'Reflex Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 9, y: 19},
        [BasePropertyType.RequiredDexterity]: 60,
        [BasePropertyType.RequiredStrength]: 35,
        [BasePropertyType.RequiredLevel]: 20,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.MaidenSpear,
    name: 'Maiden Spear',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 18, y: 24},
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.RequiredDexterity]: 40,
        [BasePropertyType.RequiredStrength]: 54,
        [BasePropertyType.RequiredLevel]: 14,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 5,
      },
    },
  },
  {
    id: ids.MaidenPike,
    name: 'Maiden Pike',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 23, y: 55},
        [BasePropertyType.Durability]: 25,
        [BasePropertyType.RequiredDexterity]: 52,
        [BasePropertyType.RequiredStrength]: 63,
        [BasePropertyType.RequiredLevel]: 20,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 5,
      },
    },
  },
  {
    id: ids.MaidenJavelin,
    name: 'Maiden Javelin',
    class: WeaponClassType.Javelin,
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 8, y: 14},
        [BasePropertyType.RequiredDexterity]: 47,
        [BasePropertyType.RequiredStrength]: 33,
        [BasePropertyType.RequiredLevel]: 17,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.AshwoodBow,
    name: 'Ashwood Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.StagBow,
    imageId: ids.StagBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 16, y: 29},
        [BasePropertyType.RequiredDexterity]: 77,
        [BasePropertyType.RequiredStrength]: 56,
        [BasePropertyType.RequiredLevel]: 29,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.CeremonialBow,
    name: 'Ceremonial Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.ReflexBow,
    imageId: ids.ReflexBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 19, y: 41},
        [BasePropertyType.RequiredDexterity]: 110,
        [BasePropertyType.RequiredStrength]: 73,
        [BasePropertyType.RequiredLevel]: 35,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.CeremonialSpear,
    name: 'Ceremonial Spear',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.MaidenSpear,
    imageId: ids.MaidenSpear,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 34, y: 51},
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.RequiredDexterity]: 80,
        [BasePropertyType.RequiredStrength]: 101,
        [BasePropertyType.RequiredLevel]: 14,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 5,
      },
    },
  },
  {
    id: ids.CeremonialPike,
    name: 'Ceremonial Pike',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.MaidenPike,
    imageId: ids.MaidenPike,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 42, y: 101},
        [BasePropertyType.Durability]: 25,
        [BasePropertyType.RequiredDexterity]: 98,
        [BasePropertyType.RequiredStrength]: 115,
        [BasePropertyType.RequiredLevel]: 38,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 5,
      },
    },
  },
  {
    id: ids.CeremonialJavelin,
    name: 'Ceremonial Javelin',
    class: WeaponClassType.Javelin,
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.MaidenJavelin,
    imageId: ids.MaidenJavelin,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 18, y: 35},
        [BasePropertyType.RequiredDexterity]: 109,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredLevel]: 26,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.MatriarchalBow,
    name: 'Matriarchal Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.StagBow,
    imageId: ids.StagBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 20, y: 47},
        [BasePropertyType.RequiredDexterity]: 187,
        [BasePropertyType.RequiredStrength]: 87,
        [BasePropertyType.RequiredLevel]: 39,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.GrandMatronBow,
    name: 'Grand Matron Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.ReflexBow,
    imageId: ids.ReflexBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 14, y: 72},
        [BasePropertyType.RequiredDexterity]: 152,
        [BasePropertyType.RequiredStrength]: 108,
        [BasePropertyType.RequiredLevel]: 58,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.MatriarchalSpear,
    name: 'Matriarchal Spear',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.MaidenSpear,
    imageId: ids.MaidenSpear,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 65, y: 95},
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.RequiredDexterity]: 142,
        [BasePropertyType.RequiredStrength]: 114,
        [BasePropertyType.RequiredLevel]: 45,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 5,
      },
    },
  },
  {
    id: ids.MatriarchalPike,
    name: 'Matriarchal Pike',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.MaidenPike,
    imageId: ids.MaidenPike,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 37, y: 153},
        [BasePropertyType.Durability]: 25,
        [BasePropertyType.RequiredDexterity]: 149,
        [BasePropertyType.RequiredStrength]: 132,
        [BasePropertyType.RequiredLevel]: 60,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 5,
      },
    },
  },
  {
    id: ids.MatriarchalJavelin,
    name: 'Matriarchal Javelin',
    class: WeaponClassType.Javelin,
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.MaidenJavelin,
    imageId: ids.MaidenJavelin,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 30, y: 54},
        [BasePropertyType.RequiredDexterity]: 151,
        [BasePropertyType.RequiredStrength]: 107,
        [BasePropertyType.RequiredLevel]: 48,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
]);
