import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  PlayerClassType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  playerClass: PlayerClassType.Amazon,
  type: ItemType.AmazonWeapon,
})([
  {
    id: ids.StagBow,
    name: 'Stag Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 7, max: 12},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 30,
        [BasePropertyType.RequiredDexterity]: 45,
        [BasePropertyType.RequiredLevel]: 14,
        [BasePropertyType.QualityLevel]: 18,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.ReflexBow,
    name: 'Reflex Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 9, max: 19},
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 35,
        [BasePropertyType.RequiredDexterity]: 60,
        [BasePropertyType.RequiredLevel]: 20,
        [BasePropertyType.QualityLevel]: 27,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.MaidenSpear,
    name: 'Maiden Spear',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 18, max: 24},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 54,
        [BasePropertyType.RequiredDexterity]: 40,
        [BasePropertyType.RequiredLevel]: 14,
        [BasePropertyType.QualityLevel]: 18,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.MaidenPike,
    name: 'Maiden Pike',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 23, max: 55},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 63,
        [BasePropertyType.RequiredDexterity]: 52,
        [BasePropertyType.RequiredLevel]: 20,
        [BasePropertyType.QualityLevel]: 27,
        [BasePropertyType.Durability]: 25,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.MaidenJavelin,
    name: 'Maiden Javelin',
    class: WeaponClassType.Javelin,
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 8, max: 14},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 33,
        [BasePropertyType.RequiredDexterity]: 47,
        [BasePropertyType.RequiredLevel]: 17,
        [BasePropertyType.QualityLevel]: 23,
      },
    },
  },
  {
    id: ids.AshwoodBow,
    name: 'Ashwood Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.StagBow,
    imageId: ids.StagBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 16, max: 29},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 56,
        [BasePropertyType.RequiredDexterity]: 77,
        [BasePropertyType.RequiredLevel]: 29,
        [BasePropertyType.QualityLevel]: 39,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.CeremonialBow,
    name: 'Ceremonial Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.ReflexBow,
    imageId: ids.ReflexBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 19, max: 41},
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 73,
        [BasePropertyType.RequiredDexterity]: 110,
        [BasePropertyType.RequiredLevel]: 35,
        [BasePropertyType.QualityLevel]: 47,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.CeremonialSpear,
    name: 'Ceremonial Spear',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.MaidenSpear,
    imageId: ids.MaidenSpear,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 34, max: 51},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 101,
        [BasePropertyType.RequiredDexterity]: 80,
        [BasePropertyType.RequiredLevel]: 14,
        [BasePropertyType.QualityLevel]: 18,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.CeremonialPike,
    name: 'Ceremonial Pike',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.MaidenPike,
    imageId: ids.MaidenPike,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 42, max: 101},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.RequiredStrength]: 115,
        [BasePropertyType.RequiredDexterity]: 98,
        [BasePropertyType.RequiredLevel]: 38,
        [BasePropertyType.QualityLevel]: 51,
        [BasePropertyType.Durability]: 25,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.CeremonialJavelin,
    name: 'Ceremonial Javelin',
    class: WeaponClassType.Javelin,
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.MaidenJavelin,
    imageId: ids.MaidenJavelin,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 18, max: 35},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 109,
        [BasePropertyType.RequiredLevel]: 26,
        [BasePropertyType.QualityLevel]: 35,
      },
    },
  },
  {
    id: ids.MatriarchalBow,
    name: 'Matriarchal Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.StagBow,
    imageId: ids.StagBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 20, max: 47},
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 87,
        [BasePropertyType.RequiredDexterity]: 187,
        [BasePropertyType.RequiredLevel]: 39,
        [BasePropertyType.QualityLevel]: 53,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.GrandMatronBow,
    name: 'Grand Matron Bow',
    class: WeaponClassType.Bow,
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.ReflexBow,
    imageId: ids.ReflexBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 14, max: 72},
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 108,
        [BasePropertyType.RequiredDexterity]: 152,
        [BasePropertyType.RequiredLevel]: 58,
        [BasePropertyType.QualityLevel]: 78,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.MatriarchalSpear,
    name: 'Matriarchal Spear',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.MaidenSpear,
    imageId: ids.MaidenSpear,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 65, max: 95},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 114,
        [BasePropertyType.RequiredDexterity]: 142,
        [BasePropertyType.RequiredLevel]: 45,
        [BasePropertyType.QualityLevel]: 61,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.MatriarchalPike,
    name: 'Matriarchal Pike',
    class: WeaponClassType.Spear,
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.MaidenPike,
    imageId: ids.MaidenPike,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 37, max: 153},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.RequiredStrength]: 132,
        [BasePropertyType.RequiredDexterity]: 149,
        [BasePropertyType.RequiredLevel]: 60,
        [BasePropertyType.QualityLevel]: 81,
        [BasePropertyType.Durability]: 25,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.MatriarchalJavelin,
    name: 'Matriarchal Javelin',
    class: WeaponClassType.Javelin,
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.MaidenJavelin,
    imageId: ids.MaidenJavelin,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 30, max: 54},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 107,
        [BasePropertyType.RequiredDexterity]: 151,
        [BasePropertyType.RequiredLevel]: 48,
        [BasePropertyType.QualityLevel]: 65,
      },
    },
  },
]);
