import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Axe,
  type: ItemType.Axe,
})([
  {
    id: ids.HandAxe,
    name: 'Hand Axe',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 3, max: 6},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.Axe,
    name: 'Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 4, max: 11},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 32,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.DoubleAxe,
    name: 'Double Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 5, max: 13},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 43,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.MilitaryPick,
    name: 'Military Pick',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 7, max: 11},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 49,
        [BasePropertyType.RequiredDexterity]: 33,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.WarAxe,
    name: 'War Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 10, max: 18},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 67,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.LargeAxe,
    name: 'Large Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 6, max: 13},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 35,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.BroadAxe,
    name: 'Broad Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 10, max: 18},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 48,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.BattleAxe,
    name: 'Battle Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 12, max: 32},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 54,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.GreatAxe,
    name: 'Great Axe',
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 9, max: 30},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 63,
        [BasePropertyType.RequiredDexterity]: 39,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.GiantAxe,
    name: 'Giant Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 22, max: 45},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 70,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.ThrowingAxe,
    name: 'Throwing Axe',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 8, max: 12},
        [BasePropertyType.Damage1H]: {min: 4, max: 7},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredDexterity]: 40,
      },
    },
  },
  {
    id: ids.BalancedAxe,
    name: 'Balanced Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 12, max: 15},
        [BasePropertyType.Damage1H]: {min: 5, max: 10},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredDexterity]: 57,
      },
    },
  },
  {
    id: ids.Hatchet,
    name: 'Hatchet',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.HandAxe,
    imageId: ids.HandAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 10, max: 21},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 25,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Cleaver,
    name: 'Cleaver',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.Axe,
    imageId: ids.Axe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 10, max: 33},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 68,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 22,
      },
    },
  },
  {
    id: ids.TwinAxe,
    name: 'Twin Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.DoubleAxe,
    imageId: ids.DoubleAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 13, max: 38},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 85,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Crowbill,
    name: 'Crowbill',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.MilitaryPick,
    imageId: ids.MilitaryPick,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 14, max: 34},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 94,
        [BasePropertyType.RequiredDexterity]: 70,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Naga,
    name: 'Naga',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.WarAxe,
    imageId: ids.WarAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 16, max: 45},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 121,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.MilitaryAxe,
    name: 'Military Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.LargeAxe,
    imageId: ids.LargeAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 14, max: 34},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 73,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.BeardedAxe,
    name: 'Bearded Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.BroadAxe,
    imageId: ids.BroadAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 21, max: 49},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 92,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Tabar,
    name: 'Tabar',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.BattleAxe,
    imageId: ids.BattleAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 24, max: 77},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 101,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.GothicAxe,
    name: 'Gothic Axe',
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.GreatAxe,
    imageId: ids.GreatAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 18, max: 70},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 115,
        [BasePropertyType.RequiredDexterity]: 79,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.AncientAxe,
    name: 'Ancient Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.GiantAxe,
    imageId: ids.GiantAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 43, max: 85},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 125,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Francisca,
    name: 'Francisca',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.ThrowingAxe,
    imageId: ids.ThrowingAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 18, max: 33},
        [BasePropertyType.Damage1H]: {min: 11, max: 22},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 80,
        [BasePropertyType.RequiredLevel]: 22,
      },
    },
  },
  {
    id: ids.Hurlbat,
    name: 'Balanced Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.BalancedAxe,
    imageId: ids.BalancedAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 24, max: 34},
        [BasePropertyType.Damage1H]: {min: 13, max: 27},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 106,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Tomahawk,
    name: 'Tomahawk',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.HandAxe,
    imageId: ids.HandAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 33, max: 58},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 125,
        [BasePropertyType.RequiredDexterity]: 67,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 40,
      },
    },
  },
  {
    id: ids.SmallCrescent,
    name: 'Small Crescent',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.Axe,
    imageId: ids.Axe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 38, max: 60},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 115,
        [BasePropertyType.RequiredDexterity]: 83,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 45,
      },
    },
  },
  {
    id: ids.EttinAxe,
    name: 'Ettin Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.DoubleAxe,
    imageId: ids.DoubleAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 33, max: 66},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 145,
        [BasePropertyType.RequiredDexterity]: 45,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 52,
      },
    },
  },
  {
    id: ids.WarSpike,
    name: 'War Spike',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.MilitaryPick,
    imageId: ids.MilitaryPick,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 30, max: 48},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 133,
        [BasePropertyType.RequiredDexterity]: 54,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 59,
      },
    },
  },
  {
    id: ids.BerserkerAxe,
    name: 'Berserker Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.WarAxe,
    imageId: ids.WarAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 24, max: 71},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 138,
        [BasePropertyType.RequiredDexterity]: 59,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 64,
      },
    },
  },
  {
    id: ids.FeralAxe,
    name: 'Feral Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.LargeAxe,
    imageId: ids.LargeAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 25, max: 123},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -15,
        [BasePropertyType.RequiredStrength]: 196,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 42,
      },
    },
  },
  {
    id: ids.SilverEdgedAxe,
    name: 'Silver-Edged Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.BroadAxe,
    imageId: ids.BroadAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 62, max: 110},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 166,
        [BasePropertyType.RequiredDexterity]: 65,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 48,
      },
    },
  },
  {
    id: ids.Decapitator,
    name: 'Decapitator',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.BattleAxe,
    imageId: ids.BattleAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 49, max: 137},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 189,
        [BasePropertyType.RequiredDexterity]: 33,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 54,
      },
    },
  },
  {
    id: ids.ChampionAxe,
    name: 'Champion Axe',
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.GreatAxe,
    imageId: ids.GreatAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 59, max: 94},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 167,
        [BasePropertyType.RequiredDexterity]: 59,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 61,
      },
    },
  },
  {
    id: ids.GloriusAxe,
    name: 'Glorius Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.GiantAxe,
    imageId: ids.GiantAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 60, max: 124},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 164,
        [BasePropertyType.RequiredDexterity]: 55,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 66,
      },
    },
  },
  {
    id: ids.FlyingAxe,
    name: 'FlyingAxe',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.ThrowingAxe,
    imageId: ids.ThrowingAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 15, max: 66},
        [BasePropertyType.Damage1H]: {min: 17, max: 65},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 88,
        [BasePropertyType.RequiredDexterity]: 108,
        [BasePropertyType.RequiredLevel]: 42,
      },
    },
  },
  {
    id: ids.WingedAxe,
    name: 'Winged Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.BalancedAxe,
    imageId: ids.BalancedAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 7, max: 60},
        [BasePropertyType.Damage1H]: {min: 11, max: 56},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 96,
        [BasePropertyType.RequiredDexterity]: 122,
        [BasePropertyType.RequiredLevel]: 60,
      },
    },
  },
]);
