import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Axe,
  type: ItemType.Axe,
})([
  {
    id: ids.HandAxe,
    name: 'Hand Axe',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 3, y: 6},
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.Axe,
    name: 'Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 4, y: 11},
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredStrength]: 32,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.DoubleAxe,
    name: 'Double Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 5, y: 13},
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredStrength]: 43,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.MilitaryPick,
    name: 'Military Pick',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 7, y: 11},
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.RequiredDexterity]: 33,
        [BasePropertyType.RequiredStrength]: 49,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.WarAxe,
    name: 'War Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 10, y: 18},
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.RequiredStrength]: 67,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.LargeAxe,
    name: 'Large Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 6, y: 13},
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.RequiredStrength]: 35,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.BroadAxe,
    name: 'Broad Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 10, y: 18},
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.RequiredStrength]: 48,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.BattleAxe,
    name: 'Battle Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 12, y: 32},
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.RequiredStrength]: 54,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.GreatAxe,
    name: 'Great Axe',
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 9, y: 30},
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.RequiredDexterity]: 39,
        [BasePropertyType.RequiredStrength]: 63,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.GiantAxe,
    name: 'Giant Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 22, y: 45},
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.RequiredStrength]: 70,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 4,
      },
    },
  },
  {
    id: ids.ThrowingAxe,
    name: 'Throwing Axe',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 8, y: 12},
        [BasePropertyType.Damage1H]: {x: 4, y: 7},
        [BasePropertyType.RequiredDexterity]: 40,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.BalancedAxe,
    name: 'Balanced Axe',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 12, y: 15},
        [BasePropertyType.Damage1H]: {x: 5, y: 10},
        [BasePropertyType.RequiredDexterity]: 57,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.Hatchet,
    name: 'Hatchet',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.HandAxe,
    imageId: ids.HandAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 10, y: 21},
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.RequiredDexterity]: 25,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.Cleaver,
    name: 'Cleaver',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.Axe,
    imageId: ids.Axe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 10, y: 33},
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredStrength]: 68,
        [BasePropertyType.RequiredLevel]: 22,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.TwinAxe,
    name: 'Twin Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.DoubleAxe,
    imageId: ids.DoubleAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 13, y: 38},
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredStrength]: 85,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.Crowbill,
    name: 'Crowbill',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.MilitaryPick,
    imageId: ids.MilitaryPick,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 14, y: 34},
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.RequiredDexterity]: 70,
        [BasePropertyType.RequiredStrength]: 94,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.Naga,
    name: 'Naga',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.WarAxe,
    imageId: ids.WarAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 16, y: 45},
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.RequiredStrength]: 121,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.MilitaryAxe,
    name: 'Military Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.LargeAxe,
    imageId: ids.LargeAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 14, y: 34},
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.RequiredStrength]: 73,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.BeardedAxe,
    name: 'Bearded Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.BroadAxe,
    imageId: ids.BroadAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 21, y: 49},
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.RequiredStrength]: 92,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.Tabar,
    name: 'Tabar',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.BattleAxe,
    imageId: ids.BattleAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 24, y: 77},
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.RequiredStrength]: 101,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.GothicAxe,
    name: 'Gothic Axe',
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.GreatAxe,
    imageId: ids.GreatAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 18, y: 70},
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.RequiredDexterity]: 79,
        [BasePropertyType.RequiredStrength]: 115,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.AncientAxe,
    name: 'Ancient Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.GiantAxe,
    imageId: ids.GiantAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 43, y: 85},
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.RequiredStrength]: 125,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 4,
      },
    },
  },
  {
    id: ids.Francisca,
    name: 'Francisca',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.ThrowingAxe,
    imageId: ids.ThrowingAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 18, y: 33},
        [BasePropertyType.Damage1H]: {x: 11, y: 22},
        [BasePropertyType.RequiredDexterity]: 80,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredLevel]: 22,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.Hurlbat,
    name: 'Balanced Axe',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.BalancedAxe,
    imageId: ids.BalancedAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 24, y: 34},
        [BasePropertyType.Damage1H]: {x: 13, y: 27},
        [BasePropertyType.RequiredDexterity]: 106,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.Tomahawk,
    name: 'Tomahawk',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.HandAxe,
    imageId: ids.HandAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 33, y: 58},
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.RequiredStrength]: 125,
        [BasePropertyType.RequiredDexterity]: 67,
        [BasePropertyType.RequiredLevel]: 40,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.SmallCrescent,
    name: 'Small Crescent',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.Axe,
    imageId: ids.Axe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 38, y: 60},
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredDexterity]: 83,
        [BasePropertyType.RequiredStrength]: 115,
        [BasePropertyType.RequiredLevel]: 45,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.EttinAxe,
    name: 'Ettin Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.DoubleAxe,
    imageId: ids.DoubleAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 33, y: 66},
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredDexterity]: 45,
        [BasePropertyType.RequiredStrength]: 145,
        [BasePropertyType.RequiredLevel]: 52,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.WarSpike,
    name: 'War Spike',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.MilitaryPick,
    imageId: ids.MilitaryPick,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 30, y: 48},
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.RequiredDexterity]: 54,
        [BasePropertyType.RequiredStrength]: 133,
        [BasePropertyType.RequiredLevel]: 59,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.BerserkerAxe,
    name: 'Berserker Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.WarAxe,
    imageId: ids.WarAxe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 24, y: 71},
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.RequiredDexterity]: 59,
        [BasePropertyType.RequiredStrength]: 138,
        [BasePropertyType.RequiredLevel]: 64,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.FeralAxe,
    name: 'Feral Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.LargeAxe,
    imageId: ids.LargeAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 25, y: 123},
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.RequiredStrength]: 196,
        [BasePropertyType.RequiredLevel]: 42,
        [BasePropertyType.AttackSpeed]: -15,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.SilverEdgedAxe,
    name: 'Silver-Edged Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.BroadAxe,
    imageId: ids.BroadAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 62, y: 110},
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.RequiredDexterity]: 65,
        [BasePropertyType.RequiredStrength]: 166,
        [BasePropertyType.RequiredLevel]: 48,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.Decapitator,
    name: 'Decapitator',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.BattleAxe,
    imageId: ids.BattleAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 49, y: 137},
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.RequiredDexterity]: 33,
        [BasePropertyType.RequiredStrength]: 189,
        [BasePropertyType.RequiredLevel]: 54,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.ChampionAxe,
    name: 'Champion Axe',
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.GreatAxe,
    imageId: ids.GreatAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 59, y: 94},
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.RequiredDexterity]: 59,
        [BasePropertyType.RequiredStrength]: 167,
        [BasePropertyType.RequiredLevel]: 61,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.GloriusAxe,
    name: 'Glorius Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.GiantAxe,
    imageId: ids.GiantAxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 60, y: 124},
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.RequiredDexterity]: 55,
        [BasePropertyType.RequiredStrength]: 164,
        [BasePropertyType.RequiredLevel]: 66,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 4,
      },
    },
  },
  {
    id: ids.FlyingAxe,
    name: 'FlyingAxe',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.ThrowingAxe,
    imageId: ids.ThrowingAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 15, y: 66},
        [BasePropertyType.Damage1H]: {x: 17, y: 65},
        [BasePropertyType.RequiredDexterity]: 108,
        [BasePropertyType.RequiredStrength]: 88,
        [BasePropertyType.RequiredLevel]: 42,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.WingedAxe,
    name: 'Winged Axe',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.BalancedAxe,
    imageId: ids.BalancedAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 7, y: 60},
        [BasePropertyType.Damage1H]: {x: 11, y: 56},
        [BasePropertyType.RequiredDexterity]: 122,
        [BasePropertyType.RequiredStrength]: 96,
        [BasePropertyType.RequiredLevel]: 60,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
]);
