import {BasePropertyType, ItemTierType, ItemType} from '../../enums/index.js';
import ids from '../ids/index.js';
import {mapItemName} from '../utils/map-item-name.js';
import {mapItemProperties} from '../utils/map-item-properties.js';
import {mapItems} from '../utils/map-items.js';

const items = {
  [ids.Sash]: {
    id: ids.Sash,
    name: 'Sash',
    tier: ItemTierType.Normal,
    ilvl: 3,
    properties: {
      [BasePropertyType.Defense]: [2, 2],
      [BasePropertyType.PotionSlots]: 8,
      [BasePropertyType.MinimumStrength]: null,
      [BasePropertyType.Durability]: 12,
    },
  },
  [ids.LightBelt]: {
    id: ids.LightBelt,
    name: 'Light Belt',
    tier: ItemTierType.Normal,
    ilvl: 7,
    properties: {
      [BasePropertyType.Defense]: [3, 3],
      [BasePropertyType.PotionSlots]: 8,
      [BasePropertyType.MinimumStrength]: null,
      [BasePropertyType.Durability]: 14,
    },
  },
  [ids.Belt]: {
    id: ids.Belt,
    name: 'Belt',
    tier: ItemTierType.Normal,
    ilvl: 12,
    properties: {
      [BasePropertyType.Defense]: [5, 5],
      [BasePropertyType.PotionSlots]: 12,
      [BasePropertyType.MinimumStrength]: 25,
      [BasePropertyType.Durability]: 16,
    },
  },
  [ids.HeavyBelt]: {
    id: ids.HeavyBelt,
    name: 'Heavy Belt',
    tier: ItemTierType.Normal,
    ilvl: 18,
    properties: {
      [BasePropertyType.Defense]: [6, 6],
      [BasePropertyType.PotionSlots]: 12,
      [BasePropertyType.MinimumStrength]: 45,
      [BasePropertyType.Durability]: 20,
    },
  },
  [ids.PlatedBelt]: {
    id: ids.PlatedBelt,
    name: 'Plated Belt',
    tier: ItemTierType.Normal,
    ilvl: 27,
    properties: {
      [BasePropertyType.Defense]: [8, 11],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 60,
      [BasePropertyType.Durability]: 24,
    },
  },
  [ids.DemonhideSash]: {
    id: ids.DemonhideSash,
    name: 'Demonhide Sash',
    tier: ItemTierType.Exceptional,
    clvl: 24,
    ilvl: 36,
    baseId: ids.Sash,
    imageId: ids.Sash,
    properties: {
      [BasePropertyType.Defense]: [29, 34],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 20,
      [BasePropertyType.Durability]: 12,
    },
  },
  [ids.SharksinBelt]: {
    id: ids.SharksinBelt,
    name: 'Sharkskin Belt',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    ilvl: 39,
    baseId: ids.LightBelt,
    imageId: ids.LightBelt,
    properties: {
      [BasePropertyType.Defense]: [31, 36],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 20,
      [BasePropertyType.Durability]: 14,
    },
  },
  [ids.MeshBelt]: {
    id: ids.MeshBelt,
    name: 'Mesh Belt',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    ilvl: 43,
    baseId: ids.Belt,
    imageId: ids.Belt,
    properties: {
      [BasePropertyType.Defense]: [35, 40],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 58,
      [BasePropertyType.Durability]: 16,
    },
  },
  [ids.BattleBelt]: {
    id: ids.BattleBelt,
    name: 'Battle Belt',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    ilvl: 49,
    baseId: ids.HeavyBelt,
    imageId: ids.HeavyBelt,
    properties: {
      [BasePropertyType.Defense]: [37, 42],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 88,
      [BasePropertyType.Durability]: 18,
    },
  },
  [ids.WarBelt]: {
    id: ids.WarBelt,
    name: 'War Belt',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    ilvl: 54,
    baseId: ids.PlatedBelt,
    imageId: ids.PlatedBelt,
    properties: {
      [BasePropertyType.Defense]: [41, 52],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 110,
      [BasePropertyType.Durability]: 24,
    },
  },
  [ids.SpiderwebSash]: {
    id: ids.SpiderwebSash,
    name: 'Spiderweb Sash',
    tier: ItemTierType.Elite,
    clvl: 46,
    ilvl: 61,
    baseId: ids.Sash,
    imageId: ids.Sash,
    properties: {
      [BasePropertyType.Defense]: [55, 62],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 50,
      [BasePropertyType.Durability]: 12,
    },
  },
  [ids.VampirefangBelt]: {
    id: ids.VampirefangBelt,
    name: 'Vampirefang Belt',
    tier: ItemTierType.Elite,
    clvl: 51,
    ilvl: 68,
    baseId: ids.LightBelt,
    imageId: ids.LightBelt,
    properties: {
      [BasePropertyType.Defense]: [56, 63],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 50,
      [BasePropertyType.Durability]: 14,
    },
  },
  [ids.MithrilCoil]: {
    id: ids.MithrilCoil,
    name: 'Mithril Coil',
    tier: ItemTierType.Elite,
    clvl: 56,
    ilvl: 75,
    baseId: ids.Belt,
    imageId: ids.Belt,
    properties: {
      [BasePropertyType.Defense]: [58, 65],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 106,
      [BasePropertyType.Durability]: 16,
    },
  },
  [ids.TrollBelt]: {
    id: ids.TrollBelt,
    name: 'Troll Belt',
    tier: ItemTierType.Elite,
    clvl: 62,
    ilvl: 82,
    baseId: ids.HeavyBelt,
    imageId: ids.HeavyBelt,
    properties: {
      [BasePropertyType.Defense]: [59, 66],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 151,
      [BasePropertyType.Durability]: 18,
    },
  },
  [ids.ColossusGirdle]: {
    id: ids.ColossusGirdle,
    name: 'Colossus Girdle',
    tier: ItemTierType.Elite,
    clvl: 67,
    ilvl: 85,
    baseId: ids.PlatedBelt,
    imageId: ids.PlatedBelt,
    properties: {
      [BasePropertyType.Defense]: [61, 71],
      [BasePropertyType.PotionSlots]: 16,
      [BasePropertyType.MinimumStrength]: 185,
      [BasePropertyType.Durability]: 24,
    },
  },
};

export default mapItems({
  type: ItemType.Belt,
  size: [1, 2],
  mapDescription: (item) => [[mapItemName(item), ...mapItemProperties(item)]],
})(items);
