import {
  ArmorClassType,
  BasePropertyType,
  ItemTierType,
  ItemType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  size: [3, 2],
  type: ItemType.BodyArmor,
})([
  {
    id: ids.QuiltedArmor,
    name: 'Quilted Armor',
    tier: ItemTierType.Normal,
    armorType: ArmorClassType.Light,
    clvl: 5,
    qlvl: 1,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [8, 11],
        [BasePropertyType.RequiredStrength]: 12,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.LeatherArmor,
    name: 'Leather Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    qlvl: 3,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [14, 17],
        [BasePropertyType.RequiredStrength]: 15,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.HardLeatherArmor,
    name: 'Hard Leather Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    qlvl: 5,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [21, 24],
        [BasePropertyType.RequiredStrength]: 20,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.StuddedLeather,
    name: 'Studded Leather',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    qlvl: 8,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [32, 35],
        [BasePropertyType.RequiredStrength]: 27,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.RingMail,
    name: 'Ring Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    qlvl: 11,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [45, 48],
        [BasePropertyType.RequiredStrength]: 36,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.ScaleMail,
    name: 'Scale Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    qlvl: 13,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [57, 60],
        [BasePropertyType.RequiredStrength]: 44,
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.ChainMail,
    name: 'Chain Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    qlvl: 15,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [72, 75],
        [BasePropertyType.RequiredStrength]: 48,
        [BasePropertyType.Durability]: 45,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.BreastPlate,
    name: 'Breast Plate',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    qlvl: 18,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [65, 68],
        [BasePropertyType.RequiredStrength]: 30,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.SplintMail,
    name: 'Splint Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    qlvl: 20,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [90, 95],
        [BasePropertyType.RequiredStrength]: 51,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.PlateMail,
    name: 'Plate Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    qlvl: 24,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [108, 116],
        [BasePropertyType.RequiredStrength]: 65,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.FieldPlate,
    name: 'Field Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    qlvl: 28,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [101, 105],
        [BasePropertyType.RequiredStrength]: 55,
        [BasePropertyType.Durability]: 48,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.GothicPlate,
    name: 'Gothic Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    qlvl: 32,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [128, 135],
        [BasePropertyType.RequiredStrength]: 70,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.LightPlate,
    name: 'Light Plate',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    qlvl: 35,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [90, 107],
        [BasePropertyType.RequiredStrength]: 41,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.FullPlateMail,
    name: 'Full Plate Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    qlvl: 37,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [150, 161],
        [BasePropertyType.RequiredStrength]: 80,
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.AncientArmor,
    name: 'Ancient Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    qlvl: 40,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [218, 233],
        [BasePropertyType.RequiredStrength]: 100,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.GhostArmor,
    name: 'Ghost Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    clvl: 22,
    qlvl: 34,
    baseId: ids.QuiltedArmor,
    imageId: ids.QuiltedArmor,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [102, 117],
        [BasePropertyType.RequiredStrength]: 38,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.SerpentskinArmor,
    name: 'Serpentskin Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    clvl: 24,
    qlvl: 36,
    baseId: ids.LeatherArmor,
    imageId: ids.LeatherArmor,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [111, 126],
        [BasePropertyType.RequiredStrength]: 43,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.DemonhideArmor,
    name: 'Demonhide Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 37,
    baseId: ids.HardLeatherArmor,
    imageId: ids.HardLeatherArmor,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [122, 136],
        [BasePropertyType.RequiredStrength]: 50,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.TrellisedArmor,
    name: 'Trellised Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 40,
    baseId: ids.StuddedLeather,
    imageId: ids.StuddedLeather,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [138, 153],
        [BasePropertyType.RequiredStrength]: 61,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.LinkedMail,
    name: 'Linked Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 42,
    baseId: ids.ChainMail,
    imageId: ids.ChainMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [158, 172],
        [BasePropertyType.RequiredStrength]: 74,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.TigulatedMail,
    name: 'Tigulated Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 43,
    baseId: ids.ScaleMail,
    imageId: ids.ScaleMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [176, 190],
        [BasePropertyType.RequiredStrength]: 86,
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.MeshArmor,
    name: 'Mesh Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 45,
    baseId: ids.RingMail,
    imageId: ids.RingMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [198, 213],
        [BasePropertyType.RequiredStrength]: 92,
        [BasePropertyType.Durability]: 45,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Cuirass,
    name: 'Cuirass',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 47,
    baseId: ids.BreastPlate,
    imageId: ids.BreastPlate,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [188, 202],
        [BasePropertyType.RequiredStrength]: 65,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.RussetArmor,
    name: 'Russet Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 49,
    baseId: ids.SplintMail,
    imageId: ids.SplintMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [225, 243],
        [BasePropertyType.RequiredStrength]: 97,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.TemplarCoat,
    name: 'Templar Coat',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 52,
    baseId: ids.PlateMail,
    imageId: ids.PlateMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [252, 274],
        [BasePropertyType.RequiredStrength]: 118,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.SharktoothArmor,
    name: 'Sharktooth Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 55,
    baseId: ids.FieldPlate,
    imageId: ids.FieldPlate,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [242, 258],
        [BasePropertyType.RequiredStrength]: 103,
        [BasePropertyType.Durability]: 48,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.EmbossedPlate,
    name: 'Embossed Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 58,
    baseId: ids.GothicPlate,
    imageId: ids.GothicPlate,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [282, 303],
        [BasePropertyType.RequiredStrength]: 125,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.MagePlate,
    name: 'Mage Plate',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 60,
    baseId: ids.LightPlate,
    imageId: ids.LightPlate,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [225, 261],
        [BasePropertyType.RequiredStrength]: 55,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.ChaosArmor,
    name: 'Chaos Armor',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 64,
    baseId: ids.FullPlateMail,
    imageId: ids.FullPlateMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [315, 342],
        [BasePropertyType.RequiredStrength]: 140,
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.OrnatePlate,
    name: 'Ornate Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 64,
    baseId: ids.AncientArmor,
    imageId: ids.AncientArmor,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [417, 450],
        [BasePropertyType.RequiredStrength]: 170,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.DuskShroud,
    name: 'Dusk Shroud',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    clvl: 49,
    qlvl: 65,
    baseId: ids.QuiltedArmor,
    imageId: ids.QuiltedArmor,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [361, 467],
        [BasePropertyType.RequiredStrength]: 77,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.Wyrmhide,
    name: 'Wyrmhide',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    clvl: 50,
    qlvl: 67,
    baseId: ids.LeatherArmor,
    imageId: ids.LeatherArmor,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [364, 470],
        [BasePropertyType.RequiredStrength]: 84,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.ScarabHusk,
    name: 'Scarab Husk',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    clvl: 51,
    qlvl: 68,
    baseId: ids.HardLeatherArmor,
    imageId: ids.HardLeatherArmor,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [369, 474],
        [BasePropertyType.RequiredStrength]: 95,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.WireFleece,
    name: 'Wire Fleece',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    clvl: 53,
    qlvl: 70,
    baseId: ids.StuddedLeather,
    imageId: ids.StuddedLeather,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [375, 481],
        [BasePropertyType.RequiredStrength]: 111,
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.DiamondMail,
    name: 'Diamond Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    clvl: 54,
    qlvl: 72,
    baseId: ids.ChainMail,
    imageId: ids.ChainMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [383, 489],
        [BasePropertyType.RequiredStrength]: 131,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.LoricatedMail,
    name: 'Loricated Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    clvl: 55,
    qlvl: 73,
    baseId: ids.ScaleMail,
    imageId: ids.ScaleMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [390, 496],
        [BasePropertyType.RequiredStrength]: 149,
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.Boneweave,
    name: 'Boneweave',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    clvl: 47,
    qlvl: 62,
    baseId: ids.RingMail,
    imageId: ids.RingMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [399, 505],
        [BasePropertyType.RequiredStrength]: 158,
        [BasePropertyType.Durability]: 45,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.GreatHauberk,
    name: 'Great Hauberk',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    clvl: 56,
    qlvl: 75,
    baseId: ids.BreastPlate,
    imageId: ids.BreastPlate,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [395, 501],
        [BasePropertyType.RequiredStrength]: 118,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.BalrogSkin,
    name: 'Balrog Skin',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    clvl: 57,
    qlvl: 76,
    baseId: ids.SplintMail,
    imageId: ids.SplintMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [410, 517],
        [BasePropertyType.RequiredStrength]: 165,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.HellforgePlate,
    name: 'Hellforge Plate',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    clvl: 59,
    qlvl: 78,
    baseId: ids.PlateMail,
    imageId: ids.PlateMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [421, 530],
        [BasePropertyType.RequiredStrength]: 196,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.KrakenShell,
    name: 'Kraken Shell',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    clvl: 61,
    qlvl: 81,
    baseId: ids.FieldPlate,
    imageId: ids.FieldPlate,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [417, 523],
        [BasePropertyType.RequiredStrength]: 174,
        [BasePropertyType.Durability]: 48,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.LacqueredPlate,
    name: 'Lacquered Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    clvl: 62,
    qlvl: 82,
    baseId: ids.GothicPlate,
    imageId: ids.GothicPlate,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [433, 541],
        [BasePropertyType.RequiredStrength]: 208,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.ArchonPlate,
    name: 'Archon Plate',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    clvl: 63,
    qlvl: 84,
    baseId: ids.LightPlate,
    imageId: ids.LightPlate,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [410, 524],
        [BasePropertyType.RequiredStrength]: 103,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.ShadowPlate,
    name: 'Shadow Plate',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    clvl: 64,
    qlvl: 83,
    baseId: ids.FullPlateMail,
    imageId: ids.FullPlateMail,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [446, 557],
        [BasePropertyType.RequiredStrength]: 230,
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.SacredArmor,
    name: 'Sacred Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    clvl: 66,
    qlvl: 85,
    baseId: ids.AncientArmor,
    imageId: ids.AncientArmor,
    properties: {
      base: {
        [BasePropertyType.ArmorDefense]: [487, 600],
        [BasePropertyType.RequiredStrength]: 232,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
]);
