import {
  ArmorClassType,
  BasePropertyType,
  ItemTierType,
  ItemType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  size: [3, 2],
  type: ItemType.BodyArmor,
})([
  {
    id: ids.QuiltedArmor,
    name: 'Quilted Armor',
    tier: ItemTierType.Normal,
    armorType: ArmorClassType.Light,
    properties: {
      base: {
        [BasePropertyType.Defense]: [8, 11],
        [BasePropertyType.RequiredStrength]: 12,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.QualityLevel]: 1,
      },
    },
  },
  {
    id: ids.LeatherArmor,
    name: 'Leather Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [14, 17],
        [BasePropertyType.RequiredStrength]: 15,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.QualityLevel]: 3,
      },
    },
  },
  {
    id: ids.HardLeatherArmor,
    name: 'Hard Leather Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [21, 24],
        [BasePropertyType.RequiredStrength]: 20,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.QualityLevel]: 5,
      },
    },
  },
  {
    id: ids.StuddedLeather,
    name: 'Studded Leather',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [32, 35],
        [BasePropertyType.RequiredStrength]: 27,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.QualityLevel]: 8,
      },
    },
  },
  {
    id: ids.RingMail,
    name: 'Ring Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [45, 48],
        [BasePropertyType.RequiredStrength]: 36,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.QualityLevel]: 11,
      },
    },
  },
  {
    id: ids.ScaleMail,
    name: 'Scale Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [57, 60],
        [BasePropertyType.RequiredStrength]: 44,
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.QualityLevel]: 13,
      },
    },
  },
  {
    id: ids.ChainMail,
    name: 'Chain Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [72, 75],
        [BasePropertyType.RequiredStrength]: 48,
        [BasePropertyType.Durability]: 45,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.QualityLevel]: 15,
      },
    },
  },
  {
    id: ids.BreastPlate,
    name: 'Breast Plate',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [65, 68],
        [BasePropertyType.RequiredStrength]: 30,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.QualityLevel]: 18,
      },
    },
  },
  {
    id: ids.SplintMail,
    name: 'Splint Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [90, 95],
        [BasePropertyType.RequiredStrength]: 51,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.QualityLevel]: 20,
      },
    },
  },
  {
    id: ids.PlateMail,
    name: 'Plate Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [108, 116],
        [BasePropertyType.RequiredStrength]: 65,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.QualityLevel]: 24,
      },
    },
  },
  {
    id: ids.FieldPlate,
    name: 'Field Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [101, 105],
        [BasePropertyType.RequiredStrength]: 55,
        [BasePropertyType.Durability]: 48,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.QualityLevel]: 28,
      },
    },
  },
  {
    id: ids.GothicPlate,
    name: 'Gothic Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [128, 135],
        [BasePropertyType.RequiredStrength]: 70,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.QualityLevel]: 32,
      },
    },
  },
  {
    id: ids.LightPlate,
    name: 'Light Plate',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [90, 107],
        [BasePropertyType.RequiredStrength]: 41,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.QualityLevel]: 35,
      },
    },
  },
  {
    id: ids.FullPlateMail,
    name: 'Full Plate Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [150, 161],
        [BasePropertyType.RequiredStrength]: 80,
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.QualityLevel]: 37,
      },
    },
  },
  {
    id: ids.AncientArmor,
    name: 'Ancient Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Defense]: [218, 233],
        [BasePropertyType.RequiredStrength]: 100,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.QualityLevel]: 40,
      },
    },
  },
  {
    id: ids.GhostArmor,
    name: 'Ghost Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.QuiltedArmor,
    imageId: ids.QuiltedArmor,
    properties: {
      base: {
        [BasePropertyType.Defense]: [102, 117],
        [BasePropertyType.RequiredStrength]: 38,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 22,
        [BasePropertyType.QualityLevel]: 34,
      },
    },
  },
  {
    id: ids.SerpentskinArmor,
    name: 'Serpentskin Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.LeatherArmor,
    imageId: ids.LeatherArmor,
    properties: {
      base: {
        [BasePropertyType.Defense]: [111, 126],
        [BasePropertyType.RequiredStrength]: 43,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 24,
        [BasePropertyType.QualityLevel]: 36,
      },
    },
  },
  {
    id: ids.DemonhideArmor,
    name: 'Demonhide Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.HardLeatherArmor,
    imageId: ids.HardLeatherArmor,
    properties: {
      base: {
        [BasePropertyType.Defense]: [122, 136],
        [BasePropertyType.RequiredStrength]: 50,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 37,
      },
    },
  },
  {
    id: ids.TrellisedArmor,
    name: 'Trellised Armor',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.StuddedLeather,
    imageId: ids.StuddedLeather,
    properties: {
      base: {
        [BasePropertyType.Defense]: [138, 153],
        [BasePropertyType.RequiredStrength]: 61,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 40,
      },
    },
  },
  {
    id: ids.LinkedMail,
    name: 'Linked Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.ChainMail,
    imageId: ids.ChainMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [158, 172],
        [BasePropertyType.RequiredStrength]: 74,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 42,
      },
    },
  },
  {
    id: ids.TigulatedMail,
    name: 'Tigulated Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    baseId: ids.ScaleMail,
    imageId: ids.ScaleMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [176, 190],
        [BasePropertyType.RequiredStrength]: 86,
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 43,
      },
    },
  },
  {
    id: ids.MeshArmor,
    name: 'Mesh Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.RingMail,
    imageId: ids.RingMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [198, 213],
        [BasePropertyType.RequiredStrength]: 92,
        [BasePropertyType.Durability]: 45,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 45,
      },
    },
  },
  {
    id: ids.Cuirass,
    name: 'Cuirass',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.BreastPlate,
    imageId: ids.BreastPlate,
    properties: {
      base: {
        [BasePropertyType.Defense]: [188, 202],
        [BasePropertyType.RequiredStrength]: 65,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 47,
      },
    },
  },
  {
    id: ids.RussetArmor,
    name: 'Russet Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.SplintMail,
    imageId: ids.SplintMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [225, 243],
        [BasePropertyType.RequiredStrength]: 97,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 49,
      },
    },
  },
  {
    id: ids.TemplarCoat,
    name: 'Templar Coat',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    baseId: ids.PlateMail,
    imageId: ids.PlateMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [252, 274],
        [BasePropertyType.RequiredStrength]: 118,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 52,
      },
    },
  },
  {
    id: ids.SharktoothArmor,
    name: 'Sharktooth Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.FieldPlate,
    imageId: ids.FieldPlate,
    properties: {
      base: {
        [BasePropertyType.Defense]: [242, 258],
        [BasePropertyType.RequiredStrength]: 103,
        [BasePropertyType.Durability]: 48,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 55,
      },
    },
  },
  {
    id: ids.EmbossedPlate,
    name: 'Embossed Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.GothicPlate,
    imageId: ids.GothicPlate,
    properties: {
      base: {
        [BasePropertyType.Defense]: [282, 303],
        [BasePropertyType.RequiredStrength]: 125,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 58,
      },
    },
  },
  {
    id: ids.MagePlate,
    name: 'Mage Plate',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.LightPlate,
    imageId: ids.LightPlate,
    properties: {
      base: {
        [BasePropertyType.Defense]: [225, 261],
        [BasePropertyType.RequiredStrength]: 55,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 60,
      },
    },
  },
  {
    id: ids.ChaosArmor,
    name: 'Chaos Armor',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    baseId: ids.FullPlateMail,
    imageId: ids.FullPlateMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [315, 342],
        [BasePropertyType.RequiredStrength]: 140,
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 64,
      },
    },
  },
  {
    id: ids.OrnatePlate,
    name: 'Ornate Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.AncientArmor,
    imageId: ids.AncientArmor,
    properties: {
      base: {
        [BasePropertyType.Defense]: [417, 450],
        [BasePropertyType.RequiredStrength]: 170,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 64,
      },
    },
  },
  {
    id: ids.DuskShroud,
    name: 'Dusk Shroud',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.QuiltedArmor,
    imageId: ids.QuiltedArmor,
    properties: {
      base: {
        [BasePropertyType.Defense]: [361, 467],
        [BasePropertyType.RequiredStrength]: 77,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 49,
        [BasePropertyType.QualityLevel]: 65,
      },
    },
  },
  {
    id: ids.Wyrmhide,
    name: 'Wyrmhide',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.LeatherArmor,
    imageId: ids.LeatherArmor,
    properties: {
      base: {
        [BasePropertyType.Defense]: [364, 470],
        [BasePropertyType.RequiredStrength]: 84,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 50,
        [BasePropertyType.QualityLevel]: 67,
      },
    },
  },
  {
    id: ids.ScarabHusk,
    name: 'Scarab Husk',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.HardLeatherArmor,
    imageId: ids.HardLeatherArmor,
    properties: {
      base: {
        [BasePropertyType.Defense]: [369, 474],
        [BasePropertyType.RequiredStrength]: 95,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 51,
        [BasePropertyType.QualityLevel]: 68,
      },
    },
  },
  {
    id: ids.WireFleece,
    name: 'Wire Fleece',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.StuddedLeather,
    imageId: ids.StuddedLeather,
    properties: {
      base: {
        [BasePropertyType.Defense]: [375, 481],
        [BasePropertyType.RequiredStrength]: 111,
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 53,
        [BasePropertyType.QualityLevel]: 70,
      },
    },
  },
  {
    id: ids.DiamondMail,
    name: 'Diamond Mail',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.ChainMail,
    imageId: ids.ChainMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [383, 489],
        [BasePropertyType.RequiredStrength]: 131,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 54,
        [BasePropertyType.QualityLevel]: 72,
      },
    },
  },
  {
    id: ids.LoricatedMail,
    name: 'Loricated Mail',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    baseId: ids.ScaleMail,
    imageId: ids.ScaleMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [390, 496],
        [BasePropertyType.RequiredStrength]: 149,
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 55,
        [BasePropertyType.QualityLevel]: 73,
      },
    },
  },
  {
    id: ids.Boneweave,
    name: 'Boneweave',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.RingMail,
    imageId: ids.RingMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [399, 505],
        [BasePropertyType.RequiredStrength]: 158,
        [BasePropertyType.Durability]: 45,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 47,
        [BasePropertyType.QualityLevel]: 62,
      },
    },
  },
  {
    id: ids.GreatHauberk,
    name: 'Great Hauberk',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.BreastPlate,
    imageId: ids.BreastPlate,
    properties: {
      base: {
        [BasePropertyType.Defense]: [395, 501],
        [BasePropertyType.RequiredStrength]: 118,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 56,
        [BasePropertyType.QualityLevel]: 75,
      },
    },
  },
  {
    id: ids.BalrogSkin,
    name: 'Balrog Skin',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.SplintMail,
    imageId: ids.SplintMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [410, 517],
        [BasePropertyType.RequiredStrength]: 165,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 57,
        [BasePropertyType.QualityLevel]: 76,
      },
    },
  },
  {
    id: ids.HellforgePlate,
    name: 'Hellforge Plate',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    baseId: ids.PlateMail,
    imageId: ids.PlateMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [421, 530],
        [BasePropertyType.RequiredStrength]: 196,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 59,
        [BasePropertyType.QualityLevel]: 78,
      },
    },
  },
  {
    id: ids.KrakenShell,
    name: 'Kraken Shell',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.FieldPlate,
    imageId: ids.FieldPlate,
    properties: {
      base: {
        [BasePropertyType.Defense]: [417, 523],
        [BasePropertyType.RequiredStrength]: 174,
        [BasePropertyType.Durability]: 48,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 61,
        [BasePropertyType.QualityLevel]: 81,
      },
    },
  },
  {
    id: ids.LacqueredPlate,
    name: 'Lacquered Plate',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.GothicPlate,
    imageId: ids.GothicPlate,
    properties: {
      base: {
        [BasePropertyType.Defense]: [433, 541],
        [BasePropertyType.RequiredStrength]: 208,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 62,
        [BasePropertyType.QualityLevel]: 82,
      },
    },
  },
  {
    id: ids.ArchonPlate,
    name: 'Archon Plate',
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.LightPlate,
    imageId: ids.LightPlate,
    properties: {
      base: {
        [BasePropertyType.Defense]: [410, 524],
        [BasePropertyType.RequiredStrength]: 103,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 63,
        [BasePropertyType.QualityLevel]: 84,
      },
    },
  },
  {
    id: ids.ShadowPlate,
    name: 'Shadow Plate',
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    baseId: ids.FullPlateMail,
    imageId: ids.FullPlateMail,
    properties: {
      base: {
        [BasePropertyType.Defense]: [446, 557],
        [BasePropertyType.RequiredStrength]: 230,
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 64,
        [BasePropertyType.QualityLevel]: 83,
      },
    },
  },
  {
    id: ids.SacredArmor,
    name: 'Sacred Armor',
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.AncientArmor,
    imageId: ids.AncientArmor,
    properties: {
      base: {
        [BasePropertyType.Defense]: [487, 600],
        [BasePropertyType.RequiredStrength]: 232,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 66,
        [BasePropertyType.QualityLevel]: 85,
      },
    },
  },
]);
