import {
  ArmorClassType,
  BasePropertyType,
  ItemQualityType,
  ItemTierType,
  ItemType,
  SocketCategoryType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  size: [3, 2],
  quality: ItemQualityType.Normal,
  socketCategory: SocketCategoryType.Armor,
  type: ItemType.BodyArmor,
})([
  {
    id: ids.QuiltedArmor,
    name: 'Quilted Armor',
    tier: ItemTierType.Normal,
    class: ArmorClassType.Light,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [8, 11],
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.RequiredStrength]: 12,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.LeatherArmor,
    name: 'Leather Armor',
    class: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [14, 17],
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredStrength]: 15,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.HardLeatherArmor,
    name: 'Hard Leather Armor',
    class: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [21, 24],
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.RequiredStrength]: 20,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.StuddedLeather,
    name: 'Studded Leather',
    class: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [32, 35],
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.RequiredStrength]: 27,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.RingMail,
    name: 'Ring Mail',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [45, 48],
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.RequiredStrength]: 36,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.ScaleMail,
    name: 'Scale Mail',
    class: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [57, 60],
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.RequiredStrength]: 44,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.ChainMail,
    name: 'Chain Mail',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [72, 75],
        [BasePropertyType.Durability]: 45,
        [BasePropertyType.RequiredStrength]: 48,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.BreastPlate,
    name: 'Breast Plate',
    class: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [65, 68],
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.RequiredStrength]: 30,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.SplintMail,
    name: 'Splint Mail',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [90, 95],
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.RequiredStrength]: 51,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.PlateMail,
    name: 'Plate Mail',
    class: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [108, 116],
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 65,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.FieldPlate,
    name: 'Field Plate',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [101, 105],
        [BasePropertyType.Durability]: 48,
        [BasePropertyType.RequiredStrength]: 55,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.GothicPlate,
    name: 'Gothic Plate',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [128, 135],
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.RequiredStrength]: 70,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.LightPlate,
    name: 'Light Plate',
    class: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [90, 107],
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 41,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.FullPlateMail,
    name: 'Full Plate Mail',
    class: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [150, 161],
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.RequiredStrength]: 80,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.AncientArmor,
    name: 'Ancient Armor',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [218, 233],
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 100,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.GhostArmor,
    name: 'Ghost Armor',
    class: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.QuiltedArmor,
    imageId: ids.QuiltedArmor,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [102, 117],
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.RequiredStrength]: 38,
        [BasePropertyType.RequiredLevel]: 22,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.SerpentskinArmor,
    name: 'Serpentskin Armor',
    class: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.LeatherArmor,
    imageId: ids.LeatherArmor,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [111, 126],
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredStrength]: 43,
        [BasePropertyType.RequiredLevel]: 24,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.DemonhideArmor,
    name: 'Demonhide Armor',
    class: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.HardLeatherArmor,
    imageId: ids.HardLeatherArmor,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [122, 136],
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.RequiredStrength]: 50,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.TrellisedArmor,
    name: 'Trellised Armor',
    class: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.StuddedLeather,
    imageId: ids.StuddedLeather,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [138, 153],
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.RequiredStrength]: 61,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.LinkedMail,
    name: 'Linked Mail',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.ChainMail,
    imageId: ids.ChainMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [158, 172],
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.RequiredStrength]: 74,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.TigulatedMail,
    name: 'Tigulated Mail',
    class: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    baseId: ids.ScaleMail,
    imageId: ids.ScaleMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [176, 190],
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.RequiredStrength]: 86,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.MeshArmor,
    name: 'Mesh Armor',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.RingMail,
    imageId: ids.RingMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [198, 213],
        [BasePropertyType.Durability]: 45,
        [BasePropertyType.RequiredStrength]: 92,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Cuirass,
    name: 'Cuirass',
    class: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.BreastPlate,
    imageId: ids.BreastPlate,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [188, 202],
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.RequiredStrength]: 65,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.RussetArmor,
    name: 'Russet Armor',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.SplintMail,
    imageId: ids.SplintMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [225, 243],
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.RequiredStrength]: 97,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.TemplarCoat,
    name: 'Templar Coat',
    class: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    baseId: ids.PlateMail,
    imageId: ids.PlateMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [252, 274],
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 118,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.SharktoothArmor,
    name: 'Sharktooth Armor',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.FieldPlate,
    imageId: ids.FieldPlate,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [242, 258],
        [BasePropertyType.Durability]: 48,
        [BasePropertyType.RequiredStrength]: 103,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.EmbossedPlate,
    name: 'Embossed Plate',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.GothicPlate,
    imageId: ids.GothicPlate,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [282, 303],
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.RequiredStrength]: 125,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.MagePlate,
    name: 'Mage Plate',
    class: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.LightPlate,
    imageId: ids.LightPlate,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [225, 261],
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 55,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.ChaosArmor,
    name: 'Chaos Armor',
    class: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    baseId: ids.FullPlateMail,
    imageId: ids.FullPlateMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [315, 342],
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.RequiredStrength]: 140,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.OrnatePlate,
    name: 'Ornate Plate',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.AncientArmor,
    imageId: ids.AncientArmor,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [417, 450],
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 170,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.DuskShroud,
    name: 'Dusk Shroud',
    class: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.QuiltedArmor,
    imageId: ids.QuiltedArmor,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [361, 467],
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.RequiredStrength]: 77,
        [BasePropertyType.RequiredLevel]: 49,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.Wyrmhide,
    name: 'Wyrmhide',
    class: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.LeatherArmor,
    imageId: ids.LeatherArmor,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [364, 470],
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredStrength]: 84,
        [BasePropertyType.RequiredLevel]: 50,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.ScarabHusk,
    name: 'Scarab Husk',
    class: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.HardLeatherArmor,
    imageId: ids.HardLeatherArmor,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [369, 474],
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.RequiredStrength]: 95,
        [BasePropertyType.RequiredLevel]: 51,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.WireFleece,
    name: 'Wire Fleece',
    class: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.StuddedLeather,
    imageId: ids.StuddedLeather,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [375, 481],
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.RequiredStrength]: 111,
        [BasePropertyType.RequiredLevel]: 53,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.DiamondMail,
    name: 'Diamond Mail',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.ChainMail,
    imageId: ids.ChainMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [383, 489],
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.RequiredStrength]: 131,
        [BasePropertyType.RequiredLevel]: 54,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.LoricatedMail,
    name: 'Loricated Mail',
    class: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    baseId: ids.ScaleMail,
    imageId: ids.ScaleMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [390, 496],
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.RequiredStrength]: 149,
        [BasePropertyType.RequiredLevel]: 55,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.Boneweave,
    name: 'Boneweave',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.RingMail,
    imageId: ids.RingMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [399, 505],
        [BasePropertyType.Durability]: 45,
        [BasePropertyType.RequiredStrength]: 158,
        [BasePropertyType.RequiredLevel]: 47,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.GreatHauberk,
    name: 'Great Hauberk',
    class: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.BreastPlate,
    imageId: ids.BreastPlate,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [395, 501],
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.RequiredStrength]: 118,
        [BasePropertyType.RequiredLevel]: 56,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.BalrogSkin,
    name: 'Balrog Skin',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.SplintMail,
    imageId: ids.SplintMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [410, 517],
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.RequiredStrength]: 165,
        [BasePropertyType.RequiredLevel]: 57,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.HellforgePlate,
    name: 'Hellforge Plate',
    class: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    baseId: ids.PlateMail,
    imageId: ids.PlateMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [421, 530],
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 196,
        [BasePropertyType.RequiredLevel]: 59,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.KrakenShell,
    name: 'Kraken Shell',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.FieldPlate,
    imageId: ids.FieldPlate,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [417, 523],
        [BasePropertyType.Durability]: 48,
        [BasePropertyType.RequiredStrength]: 174,
        [BasePropertyType.RequiredLevel]: 61,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.LacqueredPlate,
    name: 'Lacquered Plate',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.GothicPlate,
    imageId: ids.GothicPlate,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [433, 541],
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.RequiredStrength]: 208,
        [BasePropertyType.RequiredLevel]: 62,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.ArchonPlate,
    name: 'Archon Plate',
    class: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.LightPlate,
    imageId: ids.LightPlate,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [410, 524],
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 103,
        [BasePropertyType.RequiredLevel]: 63,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.ShadowPlate,
    name: 'Shadow Plate',
    class: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    baseId: ids.FullPlateMail,
    imageId: ids.FullPlateMail,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [446, 557],
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.RequiredStrength]: 230,
        [BasePropertyType.RequiredLevel]: 64,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.SacredArmor,
    name: 'Sacred Armor',
    class: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.AncientArmor,
    imageId: ids.AncientArmor,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [487, 600],
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 232,
        [BasePropertyType.RequiredLevel]: 66,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
]);
