import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {createBaseItems} from '../../utils/create-base-items.js';
import ids from '../ids/index.js';

export default createBaseItems({
  class: WeaponClassType.Bow,
  type: ItemType.Bow,
})([
  {
    id: ids.ShortBow,
    name: 'Short Bow',
    tier: ItemTierType.Normal,
    qlvl: 1,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [1, 4],
        [BasePropertyType.AttackSpeed]: [5],
        [BasePropertyType.MinimumDexterity]: [15],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.HuntersBow,
    name: "Hunter's Bow",
    tier: ItemTierType.Normal,
    qlvl: 5,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [2, 6],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumDexterity]: [28],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.LongBow,
    name: 'Long Bow',
    tier: ItemTierType.Normal,
    qlvl: 8,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [3, 10],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [22],
        [BasePropertyType.MinimumDexterity]: [19],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.CompositeBow,
    name: 'Composite Bow',
    tier: ItemTierType.Normal,
    qlvl: 12,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [4, 8],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.MinimumDexterity]: [35],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.ShortBattleBow,
    name: 'Short Battle Bow',
    tier: ItemTierType.Normal,
    qlvl: 18,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [5, 11],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [30],
        [BasePropertyType.MinimumDexterity]: [40],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.LongBattleBow,
    name: 'Long Battle Bow',
    tier: ItemTierType.Normal,
    qlvl: 23,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [3, 18],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [40],
        [BasePropertyType.MinimumDexterity]: [50],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.ShortWarBow,
    name: 'Short War Bow',
    tier: ItemTierType.Normal,
    qlvl: 27,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [6, 14],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [35],
        [BasePropertyType.MinimumDexterity]: [55],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.LongWarBow,
    name: 'Long War Bow',
    tier: ItemTierType.Normal,
    qlvl: 31,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [3, 23],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [50],
        [BasePropertyType.MinimumDexterity]: [65],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.EdgeBow,
    name: 'Edge Bow',
    tier: ItemTierType.Exceptional,
    clvl: 18,
    qlvl: 30,
    size: [3, 2],
    baseId: ids.ShortBow,
    imageId: ids.ShortBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [6, 19],
        [BasePropertyType.AttackSpeed]: [5],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.MinimumDexterity]: [43],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.RazorBow,
    name: 'Razor Bow',
    tier: ItemTierType.Exceptional,
    clvl: 21,
    qlvl: 33,
    size: [3, 2],
    baseId: ids.HuntersBow,
    imageId: ids.HuntersBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [8, 22],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.MinimumDexterity]: [62],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.CedarBow,
    name: 'Cedar Bow',
    tier: ItemTierType.Exceptional,
    clvl: 23,
    qlvl: 35,
    size: [4, 2],
    baseId: ids.LongBow,
    imageId: ids.LongBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [10, 29],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [53],
        [BasePropertyType.MinimumDexterity]: [48],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.DoubleBow,
    name: 'Double Bow',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 39,
    size: [3, 2],
    baseId: ids.CompositeBow,
    imageId: ids.CompositeBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [11, 26],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [58],
        [BasePropertyType.MinimumDexterity]: [73],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.ShortSiegeBow,
    name: 'Short Siege Bow',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 43,
    size: [3, 2],
    baseId: ids.ShortBattleBow,
    imageId: ids.ShortBattleBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [13, 30],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [65],
        [BasePropertyType.MinimumDexterity]: [80],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.LargeSiegeBow,
    name: 'Large Siege Bow',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 46,
    size: [4, 2],
    baseId: ids.LongBattleBow,
    imageId: ids.LongBattleBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [10, 42],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [80],
        [BasePropertyType.MinimumDexterity]: [95],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.RuneBow,
    name: 'Rune Bow',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 49,
    size: [3, 2],
    baseId: ids.ShortWarBow,
    imageId: ids.ShortWarBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [14, 35],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [73],
        [BasePropertyType.MinimumDexterity]: [103],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.GothicBow,
    name: 'Gothic Bow',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 52,
    size: [4, 2],
    baseId: ids.LongWarBow,
    imageId: ids.LongWarBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [10, 50],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [95],
        [BasePropertyType.MinimumDexterity]: [118],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.SpiderBow,
    name: 'Spider Bow',
    tier: ItemTierType.Elite,
    clvl: 41,
    qlvl: 55,
    size: [3, 2],
    baseId: ids.ShortBow,
    imageId: ids.ShortBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [23, 50],
        [BasePropertyType.AttackSpeed]: [5],
        [BasePropertyType.MinimumStrength]: [64],
        [BasePropertyType.MinimumDexterity]: [143],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.BladeBow,
    name: 'Blade Bow',
    tier: ItemTierType.Elite,
    clvl: 45,
    qlvl: 60,
    size: [3, 2],
    baseId: ids.HuntersBow,
    imageId: ids.HuntersBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [21, 41],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [76],
        [BasePropertyType.MinimumDexterity]: [119],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.ShadowBow,
    name: 'Shadow Bow',
    tier: ItemTierType.Elite,
    clvl: 47,
    qlvl: 63,
    size: [4, 2],
    baseId: ids.LongBow,
    imageId: ids.LongBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [15, 59],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [52],
        [BasePropertyType.MinimumDexterity]: [188],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.GreatBow,
    name: 'Great Bow',
    tier: ItemTierType.Elite,
    clvl: 51,
    qlvl: 68,
    size: [3, 2],
    baseId: ids.CompositeBow,
    imageId: ids.CompositeBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [12, 52],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [121],
        [BasePropertyType.MinimumDexterity]: [107],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.DiamondBow,
    name: 'Diamond Bow',
    tier: ItemTierType.Elite,
    clvl: 54,
    qlvl: 72,
    size: [3, 2],
    baseId: ids.ShortBattleBow,
    imageId: ids.ShortBattleBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [33, 40],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [89],
        [BasePropertyType.MinimumDexterity]: [132],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.CrusaderBow,
    name: 'Crusader Bow',
    tier: ItemTierType.Elite,
    clvl: 57,
    qlvl: 77,
    size: [4, 2],
    baseId: ids.LongBattleBow,
    imageId: ids.LongBattleBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [15, 63],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [97],
        [BasePropertyType.MinimumDexterity]: [121],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.WardBow,
    name: 'Ward Bow',
    tier: ItemTierType.Elite,
    clvl: 60,
    qlvl: 80,
    size: [3, 2],
    baseId: ids.ShortWarBow,
    imageId: ids.ShortWarBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [20, 53],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [72],
        [BasePropertyType.MinimumDexterity]: [146],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.HydraBow,
    name: 'Hydra Bow',
    tier: ItemTierType.Elite,
    clvl: 63,
    qlvl: 85,
    size: [4, 2],
    baseId: ids.LongWarBow,
    imageId: ids.LongWarBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [10, 68],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [134],
        [BasePropertyType.MinimumDexterity]: [167],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
]);
