import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Bow,
  type: ItemType.Bow,
})([
  {
    id: ids.ShortBow,
    name: 'Short Bow',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 1, max: 4},
        [BasePropertyType.AttackSpeed]: 5,
        [BasePropertyType.RequiredDexterity]: 15,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.QualityLevel]: 1,
      },
    },
  },
  {
    id: ids.HuntersBow,
    name: "Hunter's Bow",
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 2, max: 6},
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredDexterity]: 28,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.QualityLevel]: 5,
      },
    },
  },
  {
    id: ids.LongBow,
    name: 'Long Bow',
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 3, max: 10},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 22,
        [BasePropertyType.RequiredDexterity]: 19,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.QualityLevel]: 8,
      },
    },
  },
  {
    id: ids.CompositeBow,
    name: 'Composite Bow',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 4, max: 8},
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 35,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.QualityLevel]: 12,
      },
    },
  },
  {
    id: ids.ShortBattleBow,
    name: 'Short Battle Bow',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 5, max: 11},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 30,
        [BasePropertyType.RequiredDexterity]: 40,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.QualityLevel]: 18,
      },
    },
  },
  {
    id: ids.LongBattleBow,
    name: 'Long Battle Bow',
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 3, max: 18},
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 40,
        [BasePropertyType.RequiredDexterity]: 50,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.QualityLevel]: 23,
      },
    },
  },
  {
    id: ids.ShortWarBow,
    name: 'Short War Bow',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 6, max: 14},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 35,
        [BasePropertyType.RequiredDexterity]: 55,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.QualityLevel]: 27,
      },
    },
  },
  {
    id: ids.LongWarBow,
    name: 'Long War Bow',
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 3, max: 23},
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 50,
        [BasePropertyType.RequiredDexterity]: 65,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.QualityLevel]: 31,
      },
    },
  },
  {
    id: ids.EdgeBow,
    name: 'Edge Bow',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.ShortBow,
    imageId: ids.ShortBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 6, max: 19},
        [BasePropertyType.AttackSpeed]: 5,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 43,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 18,
        [BasePropertyType.QualityLevel]: 30,
      },
    },
  },
  {
    id: ids.RazorBow,
    name: 'Razor Bow',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.HuntersBow,
    imageId: ids.HuntersBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 8, max: 22},
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 62,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 21,
        [BasePropertyType.QualityLevel]: 33,
      },
    },
  },
  {
    id: ids.CedarBow,
    name: 'Cedar Bow',
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.LongBow,
    imageId: ids.LongBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 10, max: 29},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 53,
        [BasePropertyType.RequiredDexterity]: 48,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 23,
        [BasePropertyType.QualityLevel]: 35,
      },
    },
  },
  {
    id: ids.DoubleBow,
    name: 'Double Bow',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.CompositeBow,
    imageId: ids.CompositeBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 11, max: 26},
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 58,
        [BasePropertyType.RequiredDexterity]: 73,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 39,
      },
    },
  },
  {
    id: ids.ShortSiegeBow,
    name: 'Short Siege Bow',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.ShortBattleBow,
    imageId: ids.ShortBattleBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 13, max: 30},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 65,
        [BasePropertyType.RequiredDexterity]: 80,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 43,
      },
    },
  },
  {
    id: ids.LargeSiegeBow,
    name: 'Large Siege Bow',
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.LongBattleBow,
    imageId: ids.LongBattleBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 10, max: 42},
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 80,
        [BasePropertyType.RequiredDexterity]: 95,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 46,
      },
    },
  },
  {
    id: ids.RuneBow,
    name: 'Rune Bow',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.ShortWarBow,
    imageId: ids.ShortWarBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 14, max: 35},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 73,
        [BasePropertyType.RequiredDexterity]: 103,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 49,
      },
    },
  },
  {
    id: ids.GothicBow,
    name: 'Gothic Bow',
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.LongWarBow,
    imageId: ids.LongWarBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 10, max: 50},
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 95,
        [BasePropertyType.RequiredDexterity]: 118,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 52,
      },
    },
  },
  {
    id: ids.SpiderBow,
    name: 'Spider Bow',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.ShortBow,
    imageId: ids.ShortBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 23, max: 50},
        [BasePropertyType.AttackSpeed]: 5,
        [BasePropertyType.RequiredStrength]: 64,
        [BasePropertyType.RequiredDexterity]: 143,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 41,
        [BasePropertyType.QualityLevel]: 55,
      },
    },
  },
  {
    id: ids.BladeBow,
    name: 'Blade Bow',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.HuntersBow,
    imageId: ids.HuntersBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 21, max: 41},
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 76,
        [BasePropertyType.RequiredDexterity]: 119,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 45,
        [BasePropertyType.QualityLevel]: 60,
      },
    },
  },
  {
    id: ids.ShadowBow,
    name: 'Shadow Bow',
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.LongBow,
    imageId: ids.LongBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 15, max: 59},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 52,
        [BasePropertyType.RequiredDexterity]: 188,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 47,
        [BasePropertyType.QualityLevel]: 63,
      },
    },
  },
  {
    id: ids.GreatBow,
    name: 'Great Bow',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.CompositeBow,
    imageId: ids.CompositeBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 12, max: 52},
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 121,
        [BasePropertyType.RequiredDexterity]: 107,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 51,
        [BasePropertyType.QualityLevel]: 68,
      },
    },
  },
  {
    id: ids.DiamondBow,
    name: 'Diamond Bow',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.ShortBattleBow,
    imageId: ids.ShortBattleBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 33, max: 40},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 89,
        [BasePropertyType.RequiredDexterity]: 132,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 54,
        [BasePropertyType.QualityLevel]: 72,
      },
    },
  },
  {
    id: ids.CrusaderBow,
    name: 'Crusader Bow',
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.LongBattleBow,
    imageId: ids.LongBattleBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 15, max: 63},
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 97,
        [BasePropertyType.RequiredDexterity]: 121,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 57,
        [BasePropertyType.QualityLevel]: 77,
      },
    },
  },
  {
    id: ids.WardBow,
    name: 'Ward Bow',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.ShortWarBow,
    imageId: ids.ShortWarBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 20, max: 53},
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 72,
        [BasePropertyType.RequiredDexterity]: 146,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 60,
        [BasePropertyType.QualityLevel]: 80,
      },
    },
  },
  {
    id: ids.HydraBow,
    name: 'Hydra Bow',
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.LongWarBow,
    imageId: ids.LongWarBow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 10, max: 68},
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 134,
        [BasePropertyType.RequiredDexterity]: 167,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 63,
        [BasePropertyType.QualityLevel]: 85,
      },
    },
  },
]);
