import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Crossbow,
  type: ItemType.Crossbow,
})([
  {
    id: ids.LightCrossbow,
    name: 'Light Crossbow',
    tier: ItemTierType.Normal,
    qlvl: 6,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [6, 9],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [21],
        [BasePropertyType.MinimumDexterity]: [27],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.Crossbow,
    name: 'Crossbow',
    tier: ItemTierType.Normal,
    qlvl: 15,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [9, 16],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [40],
        [BasePropertyType.MinimumDexterity]: [33],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.HeavyCrossbow,
    name: 'Heavy Crossbow',
    tier: ItemTierType.Normal,
    qlvl: 24,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [14, 26],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [60],
        [BasePropertyType.MinimumDexterity]: [40],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.RepeatingCrossbow,
    name: 'Repeating Crossbow',
    tier: ItemTierType.Normal,
    qlvl: 33,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [6, 12],
        [BasePropertyType.AttackSpeed]: [-40],
        [BasePropertyType.MinimumStrength]: [40],
        [BasePropertyType.MinimumDexterity]: [50],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.Arbalest,
    name: 'Arbalest',
    tier: ItemTierType.Exceptional,
    clvl: 22,
    qlvl: 34,
    size: [3, 2],
    baseId: ids.LightCrossbow,
    imageId: ids.LightCrossbow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [14, 27],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [52],
        [BasePropertyType.MinimumDexterity]: [61],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.SiegeCrossbow,
    name: 'Siege Crossbow',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 40,
    size: [3, 2],
    baseId: ids.Crossbow,
    imageId: ids.Crossbow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [20, 42],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [80],
        [BasePropertyType.MinimumDexterity]: [70],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.Ballista,
    name: 'Ballista',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 47,
    size: [4, 2],
    baseId: ids.HeavyCrossbow,
    imageId: ids.HeavyCrossbow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [35, 55],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [110],
        [BasePropertyType.MinimumDexterity]: [80],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.ChuKoNu,
    name: 'Chu-Ko-Nu',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 54,
    size: [3, 2],
    baseId: ids.RepeatingCrossbow,
    imageId: ids.RepeatingCrossbow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [14, 32],
        [BasePropertyType.AttackSpeed]: [-60],
        [BasePropertyType.MinimumStrength]: [80],
        [BasePropertyType.MinimumDexterity]: [95],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.PelletBow,
    name: 'Pellet Bow',
    tier: ItemTierType.Elite,
    clvl: 42,
    qlvl: 57,
    size: [3, 2],
    baseId: ids.LightCrossbow,
    imageId: ids.LightCrossbow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [28, 73],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [83],
        [BasePropertyType.MinimumDexterity]: [155],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.GorgonCrossbow,
    name: 'Gorgon Crossbow',
    tier: ItemTierType.Elite,
    clvl: 50,
    qlvl: 67,
    size: [3, 2],
    baseId: ids.Crossbow,
    imageId: ids.Crossbow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [25, 87],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [117],
        [BasePropertyType.MinimumDexterity]: [105],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.ColossusCrossbow,
    name: 'Colossus Crossbow',
    tier: ItemTierType.Elite,
    clvl: 56,
    qlvl: 75,
    size: [4, 2],
    baseId: ids.HeavyCrossbow,
    imageId: ids.HeavyCrossbow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [32, 91],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [163],
        [BasePropertyType.MinimumDexterity]: [77],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.DemonCrossbow,
    name: 'Demon Crossbow',
    tier: ItemTierType.Elite,
    clvl: 63,
    qlvl: 84,
    size: [3, 2],
    baseId: ids.RepeatingCrossbow,
    imageId: ids.RepeatingCrossbow,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [26, 40],
        [BasePropertyType.AttackSpeed]: [-60],
        [BasePropertyType.MinimumStrength]: [141],
        [BasePropertyType.MinimumDexterity]: [98],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
]);
