import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Dagger,
  type: ItemType.Dagger,
})([
  {
    id: ids.Dagger,
    name: 'Dagger',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 1, max: 4},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.Durability]: 16,
        [BasePropertyType.MaxSockets]: 1,
      },
    },
  },
  {
    id: ids.Dirk,
    name: 'Dirk',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 3, max: 9},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredDexterity]: 25,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 1,
      },
    },
  },
  {
    id: ids.Kris,
    name: 'Kris',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 2, max: 11},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredDexterity]: 45,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Blade,
    name: 'Blade',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 4, max: 15},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 35,
        [BasePropertyType.RequiredDexterity]: 51,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.ThrowingKnife,
    name: 'Throwing Knife',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 4, max: 9},
        [BasePropertyType.Damage1H]: {min: 2, max: 3},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredDexterity]: 21,
      },
    },
  },
  {
    id: ids.BalancedKnife,
    name: 'Balanced Knife',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 6, max: 11},
        [BasePropertyType.Damage1H]: {min: 1, max: 8},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredDexterity]: 51,
      },
    },
  },
  {
    id: ids.Poignard,
    name: 'Poignard',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.Dagger,
    imageId: ids.Dagger,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 6, max: 18},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.Durability]: 16,
        [BasePropertyType.MaxSockets]: 1,
        [BasePropertyType.RequiredLevel]: 19,
      },
    },
  },
  {
    id: ids.Rondel,
    name: 'Rondel',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.Dirk,
    imageId: ids.Dirk,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 10, max: 26},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 58,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 1,
        [BasePropertyType.RequiredLevel]: 24,
      },
    },
  },
  {
    id: ids.Cinquedeas,
    name: 'Cinquedeas',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.Kris,
    imageId: ids.Kris,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 15, max: 31},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 88,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Stiletto,
    name: 'Stiletto',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.Blade,
    imageId: ids.Blade,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 19, max: 36},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 73,
        [BasePropertyType.RequiredDexterity]: 97,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.BattleDart,
    name: 'Battle Dart',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.ThrowingKnife,
    imageId: ids.ThrowingKnife,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 11, max: 24},
        [BasePropertyType.Damage1H]: {min: 8, max: 16},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 52,
        [BasePropertyType.RequiredLevel]: 19,
      },
    },
  },
  {
    id: ids.WarDart,
    name: 'War Dart',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.BalancedKnife,
    imageId: ids.BalancedKnife,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 14, max: 27},
        [BasePropertyType.Damage1H]: {min: 6, max: 24},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 97,
        [BasePropertyType.RequiredLevel]: 22,
      },
    },
  },
  {
    id: ids.BoneKnife,
    name: 'Bone Knife',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.Dagger,
    imageId: ids.Dagger,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 23, max: 49},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 38,
        [BasePropertyType.RequiredDexterity]: 75,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 1,
        [BasePropertyType.RequiredLevel]: 43,
      },
    },
  },
  {
    id: ids.MithrilPoint,
    name: 'Mithril Point',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.Dirk,
    imageId: ids.Dirk,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 37, max: 53},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 55,
        [BasePropertyType.RequiredDexterity]: 98,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 1,
        [BasePropertyType.RequiredLevel]: 52,
      },
    },
  },
  {
    id: ids.FangedKnife,
    name: 'Fanged Knife',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.Kris,
    imageId: ids.Kris,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 15, max: 57},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 42,
        [BasePropertyType.RequiredDexterity]: 86,
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 62,
      },
    },
  },
  {
    id: ids.LegendSpike,
    name: 'Legend Spike',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.Blade,
    imageId: ids.Blade,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 31, max: 47},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 65,
        [BasePropertyType.RequiredDexterity]: 67,
        [BasePropertyType.Durability]: 47,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 66,
      },
    },
  },
  {
    id: ids.FlyingKnife,
    name: 'Flying Knife',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.ThrowingKnife,
    imageId: ids.ThrowingKnife,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 23, max: 54},
        [BasePropertyType.Damage1H]: {min: 23, max: 54},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 48,
        [BasePropertyType.RequiredDexterity]: 141,
        [BasePropertyType.RequiredLevel]: 48,
      },
    },
  },
  {
    id: ids.WingedKnife,
    name: 'Winged Knife',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.BalancedKnife,
    imageId: ids.BalancedKnife,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {min: 23, max: 39},
        [BasePropertyType.Damage1H]: {min: 27, max: 35},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 45,
        [BasePropertyType.RequiredDexterity]: 142,
        [BasePropertyType.RequiredLevel]: 57,
      },
    },
  },
]);
