import {ItemPropertyType, ItemTierType, ItemType} from '../enums/index.js';
import ids from '../ids/index.js';
import {mapItemName} from '../utils/map-item-name.js';
import {mapItemProperties} from '../utils/map-item-properties.js';
import {mapItems} from '../utils/map-items.js';

const items = {
  [ids.Javelin]: {
    id: ids.Javelin,
    name: 'Javelin',
    tier: ItemTierType.Normal,
    ilvl: 1,
    size: [3, 1],
    properties: {
      [ItemPropertyType.Damage1H]: [1, 5],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: -10,
      [ItemPropertyType.MinimumStrength]: null,
      [ItemPropertyType.MinimumDexterity]: null,
    },
  },
  [ids.Pilum]: {
    id: ids.Pilum,
    name: 'Pilum',
    tier: ItemTierType.Normal,
    ilvl: 10,
    size: [3, 1],
    properties: {
      [ItemPropertyType.Damage1H]: [4, 9],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: 0,
      [ItemPropertyType.MinimumStrength]: null,
      [ItemPropertyType.MinimumDexterity]: 45,
    },
  },
  [ids.ShortSpear]: {
    id: ids.ShortSpear,
    name: 'Short Spear',
    tier: ItemTierType.Normal,
    ilvl: 15,
    size: [3, 1],
    properties: {
      [ItemPropertyType.Damage1H]: [2, 13],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: 10,
      [ItemPropertyType.MinimumStrength]: 40,
      [ItemPropertyType.MinimumDexterity]: 40,
    },
  },
  [ids.Glaive]: {
    id: ids.Glaive,
    name: 'Glaive',
    tier: ItemTierType.Normal,
    ilvl: 23,
    size: [4, 1],
    properties: {
      [ItemPropertyType.Damage1H]: [5, 17],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: 20,
      [ItemPropertyType.MinimumStrength]: 52,
      [ItemPropertyType.MinimumDexterity]: 35,
    },
  },
  [ids.ThrowingSpear]: {
    id: ids.ThrowingSpear,
    name: 'Throwing Spear',
    tier: ItemTierType.Normal,
    ilvl: 29,
    size: [4, 1],
    properties: {
      [ItemPropertyType.Damage1H]: [5, 15],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: -10,
      [ItemPropertyType.MinimumStrength]: null,
      [ItemPropertyType.MinimumDexterity]: 65,
    },
  },
  [ids.WarJavelin]: {
    id: ids.WarJavelin,
    name: 'War Javelin',
    tier: ItemTierType.Exceptional,
    clvl: 18,
    ilvl: 30,
    size: [3, 1],
    imageId: ids.Javelin,
    properties: {
      [ItemPropertyType.Damage1H]: [6, 19],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: -10,
      [ItemPropertyType.MinimumStrength]: 25,
      [ItemPropertyType.MinimumDexterity]: 25,
    },
  },
  [ids.GreatPilum]: {
    id: ids.GreatPilum,
    name: 'Great Pilum',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    ilvl: 37,
    size: [3, 1],
    imageId: ids.Pilum,
    properties: {
      [ItemPropertyType.Damage1H]: [11, 26],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: 0,
      [ItemPropertyType.MinimumStrength]: 25,
      [ItemPropertyType.MinimumDexterity]: 88,
    },
  },
  [ids.Simbilan]: {
    id: ids.Simbilan,
    name: 'Simbilan',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    ilvl: 40,
    size: [3, 1],
    imageId: ids.ShortSpear,
    properties: {
      [ItemPropertyType.Damage1H]: [8, 32],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: 10,
      [ItemPropertyType.MinimumStrength]: 80,
      [ItemPropertyType.MinimumDexterity]: 80,
    },
  },
  [ids.Spiculum]: {
    id: ids.Spiculum,
    name: 'Spiculum',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    ilvl: 46,
    size: [4, 1],
    imageId: ids.Glaive,
    properties: {
      [ItemPropertyType.Damage1H]: [13, 38],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: 20,
      [ItemPropertyType.MinimumStrength]: 98,
      [ItemPropertyType.MinimumDexterity]: 73,
    },
  },
  [ids.Harpoon]: {
    id: ids.Harpoon,
    name: 'Harpoon',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    ilvl: 51,
    size: [4, 1],
    imageId: ids.ThrowingSpear,
    properties: {
      [ItemPropertyType.Damage1H]: [13, 35],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: -10,
      [ItemPropertyType.MinimumStrength]: 25,
      [ItemPropertyType.MinimumDexterity]: 118,
    },
  },
  [ids.HyperionJavelin]: {
    id: ids.HyperionJavelin,
    name: 'Hyperion Javelin',
    tier: ItemTierType.Elite,
    clvl: 40,
    ilvl: 54,
    size: [3, 1],
    imageId: ids.Javelin,
    properties: {
      [ItemPropertyType.Damage1H]: [21, 57],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: -10,
      [ItemPropertyType.MinimumStrength]: 98,
      [ItemPropertyType.MinimumDexterity]: 123,
    },
  },
  [ids.StygianPilum]: {
    id: ids.StygianPilum,
    name: 'Stygian Pilum',
    tier: ItemTierType.Elite,
    clvl: 46,
    ilvl: 62,
    size: [3, 1],
    imageId: ids.Pilum,
    properties: {
      [ItemPropertyType.Damage1H]: [14, 64],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: 0,
      [ItemPropertyType.MinimumStrength]: 118,
      [ItemPropertyType.MinimumDexterity]: 112,
    },
  },
  [ids.BalrogSpear]: {
    id: ids.BalrogSpear,
    name: 'Balrog Spear',
    tier: ItemTierType.Elite,
    clvl: 53,
    ilvl: 71,
    size: [3, 1],
    imageId: ids.ShortSpear,
    properties: {
      [ItemPropertyType.Damage1H]: [33, 63],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: 10,
      [ItemPropertyType.MinimumStrength]: 127,
      [ItemPropertyType.MinimumDexterity]: 95,
    },
  },
  [ids.GhostGlaive]: {
    id: ids.GhostGlaive,
    name: 'Ghost Glaive',
    tier: ItemTierType.Elite,
    clvl: 59,
    ilvl: 69,
    size: [4, 1],
    imageId: ids.Glaive,
    properties: {
      [ItemPropertyType.Damage1H]: [19, 60],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: 20,
      [ItemPropertyType.MinimumStrength]: 89,
      [ItemPropertyType.MinimumDexterity]: 137,
    },
  },
  [ids.WingedHarpoon]: {
    id: ids.WingedHarpoon,
    name: 'Winged Harpoon',
    tier: ItemTierType.Elite,
    clvl: 65,
    ilvl: 85,
    size: [4, 1],
    imageId: ids.ThrowingSpear,
    properties: {
      [ItemPropertyType.Damage1H]: [27, 35],
      [ItemPropertyType.MeleeRange]: 3,
      [ItemPropertyType.AttackSpeed]: -10,
      [ItemPropertyType.MinimumStrength]: 76,
      [ItemPropertyType.MinimumDexterity]: 145,
    },
  },
};

export default mapItems({
  type: ItemType.Javelin,
  mapDescription: (item) => [[mapItemName(item), ...mapItemProperties(item)]],
})(items);
