import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Mace,
  type: ItemType.Mace,
})([
  {
    id: ids.Club,
    name: 'Club',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 1, y: 6},
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.SpikedClub,
    name: 'Spiked Club',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 5, y: 8},
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.Mace,
    name: 'Mace',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 3, y: 10},
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 27,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.MorningStar,
    name: 'Morning Star',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 7, y: 16},
        [BasePropertyType.Durability]: 72,
        [BasePropertyType.RequiredStrength]: 36,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.Flail,
    name: 'Flail',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 1, y: 24},
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.RequiredDexterity]: 35,
        [BasePropertyType.RequiredStrength]: 41,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.WarHammer,
    name: 'War Hammer',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 19, y: 29},
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.RequiredStrength]: 53,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.Maul,
    name: 'Maul',
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 30, y: 43},
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 69,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.GreatMaul,
    name: 'Great Maul',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 38, y: 58},
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 99,
        [BasePropertyType.AttackSpeed]: 12,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.Cudgel,
    name: 'Cudgel',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.Club,
    imageId: ids.Club,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 6, y: 21},
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredLevel]: 18,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.BarbedClub,
    name: 'Barbed Club',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.SpikedClub,
    imageId: ids.SpikedClub,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 13, y: 25},
        [BasePropertyType.Durability]: 36,
        [BasePropertyType.RequiredStrength]: 30,
        [BasePropertyType.RequiredLevel]: 20,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.FlangedMace,
    name: 'Flanged Mace',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.Mace,
    imageId: ids.Mace,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 15, y: 23},
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 61,
        [BasePropertyType.RequiredLevel]: 23,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.JaggedStar,
    name: 'Jagged Star',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.MorningStar,
    imageId: ids.MorningStar,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 20, y: 31},
        [BasePropertyType.Durability]: 72,
        [BasePropertyType.RequiredStrength]: 74,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.Knout,
    name: 'Knout',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.Flail,
    imageId: ids.Flail,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 13, y: 35},
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.RequiredDexterity]: 73,
        [BasePropertyType.RequiredStrength]: 82,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.BattleHammer,
    name: 'Battle Hammer',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.WarHammer,
    imageId: ids.WarHammer,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 35, y: 58},
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.RequiredStrength]: 100,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.WarClub,
    name: 'War Club',
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.Maul,
    imageId: ids.Maul,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 53, y: 78},
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 124,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.MartelDeFer,
    name: 'Martel de Fer',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.GreatMaul,
    imageId: ids.GreatMaul,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 61, y: 99},
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 169,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.Truncheon,
    name: 'Truncheon',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.Club,
    imageId: ids.Club,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 35, y: 43},
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.RequiredDexterity]: 43,
        [BasePropertyType.RequiredStrength]: 88,
        [BasePropertyType.RequiredLevel]: 39,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.TyrantClub,
    name: 'Tyrant Club',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.SpikedClub,
    imageId: ids.SpikedClub,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 32, y: 58},
        [BasePropertyType.Durability]: 65,
        [BasePropertyType.RequiredStrength]: 133,
        [BasePropertyType.RequiredLevel]: 42,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.ReinforcedMace,
    name: 'Reinforced Mace',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.Mace,
    imageId: ids.Mace,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 41, y: 49},
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredDexterity]: 46,
        [BasePropertyType.RequiredStrength]: 145,
        [BasePropertyType.RequiredLevel]: 47,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.DevilStar,
    name: 'Devil Star',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.MorningStar,
    imageId: ids.MorningStar,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 43, y: 53},
        [BasePropertyType.Durability]: 72,
        [BasePropertyType.RequiredDexterity]: 44,
        [BasePropertyType.RequiredStrength]: 153,
        [BasePropertyType.RequiredLevel]: 52,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.Scourge,
    name: 'Scourge',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.Flail,
    imageId: ids.Flail,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 3, y: 80},
        [BasePropertyType.Durability]: 65,
        [BasePropertyType.RequiredDexterity]: 77,
        [BasePropertyType.RequiredStrength]: 125,
        [BasePropertyType.RequiredLevel]: 57,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
  {
    id: ids.LegendaryMallet,
    name: 'Legendary Mallet',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.WarHammer,
    imageId: ids.WarHammer,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {x: 50, y: 61},
        [BasePropertyType.Durability]: 65,
        [BasePropertyType.RequiredStrength]: 189,
        [BasePropertyType.RequiredLevel]: 61,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.OgreMaul,
    name: 'Ogre Maul',
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.Maul,
    imageId: ids.Maul,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 77, y: 106},
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 225,
        [BasePropertyType.RequiredLevel]: 51,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 2,
      },
    },
  },
  {
    id: ids.ThunderMaul,
    name: 'Thunder Maul',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.GreatMaul,
    imageId: ids.GreatMaul,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {x: 33, y: 180},
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 253,
        [BasePropertyType.RequiredLevel]: 65,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.MeleeRange]: 3,
      },
    },
  },
]);
