import {
  ArmorClassType,
  BasePropertyType,
  ItemTierType,
  ItemType,
  PlayerClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: ArmorClassType.Light,
  playerClass: PlayerClassType.Necromancer,
  size: [2, 2],
  type: ItemType.NecromancerHead,
})([
  {
    id: ids.PreservedHead,
    name: 'Preserved Head',
    tier: ItemTierType.Normal,
    clvl: 3,
    qlvl: 4,
    properties: {
      base: {
        [BasePropertyType.Defense]: [2, 5],
        [BasePropertyType.BlockChance]: [23],
        [BasePropertyType.MinimumStrength]: [12],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.ZombieHead,
    name: 'Zombie Head',
    tier: ItemTierType.Normal,
    clvl: 6,
    qlvl: 8,
    properties: {
      base: {
        [BasePropertyType.Defense]: [4, 8],
        [BasePropertyType.BlockChance]: [25],
        [BasePropertyType.MinimumStrength]: [14],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.UnravellerHead,
    name: 'Unraveller Head',
    tier: ItemTierType.Normal,
    clvl: 12,
    qlvl: 16,
    properties: {
      base: {
        [BasePropertyType.Defense]: [6, 10],
        [BasePropertyType.BlockChance]: [28],
        [BasePropertyType.MinimumStrength]: [18],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.GargoyleHead,
    name: 'Gargoyle Head',
    tier: ItemTierType.Normal,
    clvl: 15,
    qlvl: 20,
    properties: {
      base: {
        [BasePropertyType.Defense]: [10, 16],
        [BasePropertyType.BlockChance]: [30],
        [BasePropertyType.MinimumStrength]: [20],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.DemonHead,
    name: 'Demon Head',
    tier: ItemTierType.Normal,
    clvl: 18,
    qlvl: 24,
    properties: {
      base: {
        [BasePropertyType.Defense]: [15, 20],
        [BasePropertyType.BlockChance]: [32],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.MummifiedTrophy,
    name: 'Mummified Trophy',
    tier: ItemTierType.Exceptional,
    clvl: 24,
    qlvl: 33,
    baseId: ids.PreservedHead,
    imageId: ids.PreservedHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [38, 48],
        [BasePropertyType.BlockChance]: [23],
        [BasePropertyType.MinimumStrength]: [38],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.FetishTrophy,
    name: 'Fetish Trophy',
    tier: ItemTierType.Exceptional,
    clvl: 29,
    qlvl: 39,
    baseId: ids.ZombieHead,
    imageId: ids.ZombieHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [41, 52],
        [BasePropertyType.BlockChance]: [25],
        [BasePropertyType.MinimumStrength]: [41],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.SextonTrophy,
    name: 'Sexton Trophy',
    tier: ItemTierType.Exceptional,
    clvl: 33,
    qlvl: 45,
    baseId: ids.UnravellerHead,
    imageId: ids.UnravellerHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [44, 55],
        [BasePropertyType.BlockChance]: [28],
        [BasePropertyType.MinimumStrength]: [47],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.CantorTrophy,
    name: 'Cantor Trophy',
    tier: ItemTierType.Exceptional,
    clvl: 36,
    qlvl: 49,
    baseId: ids.GargoyleHead,
    imageId: ids.GargoyleHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [50, 64],
        [BasePropertyType.BlockChance]: [30],
        [BasePropertyType.MinimumStrength]: [50],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.HierophantTrophy,
    name: 'Hierophant Trophy',
    tier: ItemTierType.Exceptional,
    clvl: 40,
    qlvl: 54,
    baseId: ids.DemonHead,
    imageId: ids.DemonHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [58, 70],
        [BasePropertyType.BlockChance]: [32],
        [BasePropertyType.MinimumStrength]: [58],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.MinionSkull,
    name: 'Minion Skull',
    tier: ItemTierType.Elite,
    clvl: 44,
    qlvl: 59,
    baseId: ids.PreservedHead,
    imageId: ids.PreservedHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [95, 139],
        [BasePropertyType.BlockChance]: [23],
        [BasePropertyType.MinimumStrength]: [77],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.HellspawnSkull,
    name: 'Hellspawn Skull',
    tier: ItemTierType.Elite,
    clvl: 50,
    qlvl: 67,
    baseId: ids.ZombieHead,
    imageId: ids.ZombieHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [96, 141],
        [BasePropertyType.BlockChance]: [25],
        [BasePropertyType.MinimumStrength]: [82],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.OverseerSkull,
    name: 'Overseer Skull',
    tier: ItemTierType.Elite,
    clvl: 49,
    qlvl: 66,
    baseId: ids.UnravellerHead,
    imageId: ids.UnravellerHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [98, 142],
        [BasePropertyType.BlockChance]: [28],
        [BasePropertyType.MinimumStrength]: [91],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.SuccubusSkull,
    name: 'Succubus Skull',
    tier: ItemTierType.Elite,
    clvl: 60,
    qlvl: 81,
    baseId: ids.GargoyleHead,
    imageId: ids.GargoyleHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [100, 146],
        [BasePropertyType.BlockChance]: [30],
        [BasePropertyType.MinimumStrength]: [95],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.BloodlordSkull,
    name: 'Bloodlord Skull',
    tier: ItemTierType.Elite,
    clvl: 65,
    qlvl: 85,
    baseId: ids.DemonHead,
    imageId: ids.DemonHead,
    properties: {
      base: {
        [BasePropertyType.Defense]: [103, 148],
        [BasePropertyType.BlockChance]: [32],
        [BasePropertyType.MinimumStrength]: [106],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
]);
