import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Polearm,
  size: [4, 2],
  type: ItemType.Polearm,
})([
  {
    id: ids.Bardiche,
    name: 'Bardiche',
    tier: ItemTierType.Normal,
    qlvl: 5,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [1, 27],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [40],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.Voulge,
    name: 'Voulge',
    tier: ItemTierType.Normal,
    qlvl: 11,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [6, 21],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [50],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.Scythe,
    name: 'Scythe',
    tier: ItemTierType.Normal,
    qlvl: 15,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [8, 20],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [41],
        [BasePropertyType.RequiredDexterity]: [41],
        [BasePropertyType.Durability]: [65],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.Poleaxe,
    name: 'Poleaxe',
    tier: ItemTierType.Normal,
    qlvl: 21,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [18, 39],
        [BasePropertyType.MeleeRange]: [4],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [62],
        [BasePropertyType.Durability]: [65],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.Halberd,
    name: 'Halberd',
    tier: ItemTierType.Normal,
    qlvl: 29,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [12, 45],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [75],
        [BasePropertyType.RequiredDexterity]: [47],
        [BasePropertyType.Durability]: [55],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.WarScythe,
    name: 'War Scythe',
    tier: ItemTierType.Normal,
    qlvl: 34,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [15, 36],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [80],
        [BasePropertyType.RequiredDexterity]: [80],
        [BasePropertyType.Durability]: [55],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.LochaberAxe,
    name: 'Lochaber Axe',
    tier: ItemTierType.Exceptional,
    clvl: 21,
    qlvl: 33,
    baseId: ids.Bardiche,
    imageId: ids.Bardiche,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [6, 58],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [80],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.Bill,
    name: 'Bill',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 37,
    baseId: ids.Voulge,
    imageId: ids.Voulge,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [14, 53],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [95],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.BattleScythe,
    name: 'Battle Scythe',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 40,
    baseId: ids.Scythe,
    imageId: ids.Scythe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [18, 45],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [82],
        [BasePropertyType.RequiredDexterity]: [82],
        [BasePropertyType.Durability]: [65],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.Partizan,
    name: 'Partizan',
    tier: ItemTierType.Exceptional,
    clvl: 23,
    qlvl: 35,
    baseId: ids.Poleaxe,
    imageId: ids.Poleaxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [34, 75],
        [BasePropertyType.MeleeRange]: [4],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [113],
        [BasePropertyType.RequiredDexterity]: [67],
        [BasePropertyType.Durability]: [65],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.BecDeCorbin,
    name: 'Be-De-Corbin',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 51,
    baseId: ids.Halberd,
    imageId: ids.Halberd,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [13, 85],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [133],
        [BasePropertyType.RequiredDexterity]: [91],
        [BasePropertyType.Durability]: [55],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.GrimScythe,
    name: 'Grim Scythe',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 34,
    baseId: ids.WarScythe,
    imageId: ids.WarScythe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [30, 70],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [140],
        [BasePropertyType.RequiredDexterity]: [140],
        [BasePropertyType.Durability]: [55],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.OgreAxe,
    name: 'Ogre Axe',
    tier: ItemTierType.Elite,
    clvl: 45,
    qlvl: 60,
    baseId: ids.Bardiche,
    imageId: ids.Bardiche,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [28, 145],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [195],
        [BasePropertyType.RequiredDexterity]: [75],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.ColossusVoulge,
    name: 'Colossus Voulge',
    tier: ItemTierType.Elite,
    clvl: 48,
    qlvl: 64,
    baseId: ids.Voulge,
    imageId: ids.Voulge,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [17, 165],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [210],
        [BasePropertyType.Durability]: [55],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.Thresher,
    name: 'Thresher',
    tier: ItemTierType.Elite,
    clvl: 53,
    qlvl: 71,
    baseId: ids.Scythe,
    imageId: ids.Scythe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [12, 141],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [152],
        [BasePropertyType.RequiredDexterity]: [118],
        [BasePropertyType.Durability]: [65],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.CrypticAxe,
    name: 'Cryptic Axe',
    tier: ItemTierType.Elite,
    clvl: 59,
    qlvl: 79,
    baseId: ids.Poleaxe,
    imageId: ids.Poleaxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [33, 150],
        [BasePropertyType.MeleeRange]: [4],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [165],
        [BasePropertyType.RequiredDexterity]: [103],
        [BasePropertyType.Durability]: [65],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.GreatPoleaxe,
    name: 'Great Poleaxe',
    tier: ItemTierType.Elite,
    clvl: 63,
    qlvl: 84,
    baseId: ids.Halberd,
    imageId: ids.Halberd,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [46, 127],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [179],
        [BasePropertyType.RequiredDexterity]: [99],
        [BasePropertyType.Durability]: [55],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.GiantThresher,
    name: 'Grim Thresher',
    tier: ItemTierType.Elite,
    clvl: 66,
    qlvl: 85,
    baseId: ids.WarScythe,
    imageId: ids.WarScythe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [40, 114],
        [BasePropertyType.MeleeRange]: [5],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [188],
        [BasePropertyType.RequiredDexterity]: [140],
        [BasePropertyType.Durability]: [55],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
]);
