import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Polearm,
  size: [4, 2],
  type: ItemType.Polearm,
})([
  {
    id: ids.Bardiche,
    name: 'Bardiche',
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 1, max: 27},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 40,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.QualityLevel]: 5,
      },
    },
  },
  {
    id: ids.Voulge,
    name: 'Voulge',
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 6, max: 21},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 50,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.QualityLevel]: 11,
      },
    },
  },
  {
    id: ids.Scythe,
    name: 'Scythe',
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 8, max: 20},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 41,
        [BasePropertyType.RequiredDexterity]: 41,
        [BasePropertyType.Durability]: 65,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.QualityLevel]: 15,
      },
    },
  },
  {
    id: ids.Poleaxe,
    name: 'Poleaxe',
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 18, max: 39},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 62,
        [BasePropertyType.Durability]: 65,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.QualityLevel]: 21,
      },
    },
  },
  {
    id: ids.Halberd,
    name: 'Halberd',
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 12, max: 45},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 75,
        [BasePropertyType.RequiredDexterity]: 47,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.QualityLevel]: 29,
      },
    },
  },
  {
    id: ids.WarScythe,
    name: 'War Scythe',
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 15, max: 36},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 80,
        [BasePropertyType.RequiredDexterity]: 80,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.QualityLevel]: 34,
      },
    },
  },
  {
    id: ids.LochaberAxe,
    name: 'Lochaber Axe',
    tier: ItemTierType.Exceptional,
    baseId: ids.Bardiche,
    imageId: ids.Bardiche,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 6, max: 58},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 80,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 21,
        [BasePropertyType.QualityLevel]: 33,
      },
    },
  },
  {
    id: ids.Bill,
    name: 'Bill',
    tier: ItemTierType.Exceptional,
    baseId: ids.Voulge,
    imageId: ids.Voulge,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 14, max: 53},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 95,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 37,
      },
    },
  },
  {
    id: ids.BattleScythe,
    name: 'Battle Scythe',
    tier: ItemTierType.Exceptional,
    baseId: ids.Scythe,
    imageId: ids.Scythe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 18, max: 45},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 82,
        [BasePropertyType.RequiredDexterity]: 82,
        [BasePropertyType.Durability]: 65,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 40,
      },
    },
  },
  {
    id: ids.Partizan,
    name: 'Partizan',
    tier: ItemTierType.Exceptional,
    baseId: ids.Poleaxe,
    imageId: ids.Poleaxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 34, max: 75},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 113,
        [BasePropertyType.RequiredDexterity]: 67,
        [BasePropertyType.Durability]: 65,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 23,
        [BasePropertyType.QualityLevel]: 35,
      },
    },
  },
  {
    id: ids.BecDeCorbin,
    name: 'Be-De-Corbin',
    tier: ItemTierType.Exceptional,
    baseId: ids.Halberd,
    imageId: ids.Halberd,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 13, max: 85},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 133,
        [BasePropertyType.RequiredDexterity]: 91,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 51,
      },
    },
  },
  {
    id: ids.GrimScythe,
    name: 'Grim Scythe',
    tier: ItemTierType.Exceptional,
    baseId: ids.WarScythe,
    imageId: ids.WarScythe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 30, max: 70},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 140,
        [BasePropertyType.RequiredDexterity]: 140,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.QualityLevel]: 34,
      },
    },
  },
  {
    id: ids.OgreAxe,
    name: 'Ogre Axe',
    tier: ItemTierType.Elite,
    baseId: ids.Bardiche,
    imageId: ids.Bardiche,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 28, max: 145},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 195,
        [BasePropertyType.RequiredDexterity]: 75,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 45,
        [BasePropertyType.QualityLevel]: 60,
      },
    },
  },
  {
    id: ids.ColossusVoulge,
    name: 'Colossus Voulge',
    tier: ItemTierType.Elite,
    baseId: ids.Voulge,
    imageId: ids.Voulge,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 17, max: 165},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 210,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 48,
        [BasePropertyType.QualityLevel]: 64,
      },
    },
  },
  {
    id: ids.Thresher,
    name: 'Thresher',
    tier: ItemTierType.Elite,
    baseId: ids.Scythe,
    imageId: ids.Scythe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 12, max: 141},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 152,
        [BasePropertyType.RequiredDexterity]: 118,
        [BasePropertyType.Durability]: 65,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 53,
        [BasePropertyType.QualityLevel]: 71,
      },
    },
  },
  {
    id: ids.CrypticAxe,
    name: 'Cryptic Axe',
    tier: ItemTierType.Elite,
    baseId: ids.Poleaxe,
    imageId: ids.Poleaxe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 33, max: 150},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 165,
        [BasePropertyType.RequiredDexterity]: 103,
        [BasePropertyType.Durability]: 65,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 59,
        [BasePropertyType.QualityLevel]: 79,
      },
    },
  },
  {
    id: ids.GreatPoleaxe,
    name: 'Great Poleaxe',
    tier: ItemTierType.Elite,
    baseId: ids.Halberd,
    imageId: ids.Halberd,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 46, max: 127},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 179,
        [BasePropertyType.RequiredDexterity]: 99,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 63,
        [BasePropertyType.QualityLevel]: 84,
      },
    },
  },
  {
    id: ids.GiantThresher,
    name: 'Grim Thresher',
    tier: ItemTierType.Elite,
    baseId: ids.WarScythe,
    imageId: ids.WarScythe,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 40, max: 114},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 188,
        [BasePropertyType.RequiredDexterity]: 140,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 66,
        [BasePropertyType.QualityLevel]: 85,
      },
    },
  },
]);
