import {
  ArmorClassType,
  BasePropertyType,
  ItemTierType,
  ItemType,
  SocketCategoryType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  socketCategory: SocketCategoryType.Shield,
  type: ItemType.Shield,
})([
  {
    id: ids.Buckler,
    name: 'Buckler',
    size: [2, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [4, 6],
        [BasePropertyType.BlockChance]: 30,
        [BasePropertyType.Durability]: 12,
        [BasePropertyType.RequiredStrength]: 12,
        [BasePropertyType.MaxSockets]: 1,
      },
    },
  },
  {
    id: ids.SmallShield,
    name: 'Small Shield',
    size: [2, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [8, 10],
        [BasePropertyType.BlockChance]: 35,
        [BasePropertyType.Durability]: 16,
        [BasePropertyType.RequiredStrength]: 22,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.LargeShield,
    name: 'Large Shield',
    size: [3, 2],
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [12, 14],
        [BasePropertyType.BlockChance]: 35,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.RequiredStrength]: 34,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.KiteShield,
    name: 'Kite Shield',
    size: [3, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [16, 18],
        [BasePropertyType.BlockChance]: 38,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.RequiredStrength]: 47,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.SpikedShield,
    name: 'Spiked Shield',
    size: [3, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [15, 25],
        [BasePropertyType.BlockChance]: 40,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.RequiredStrength]: 30,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.BoneShield,
    name: 'Bone Shield',
    size: [3, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [10, 30],
        [BasePropertyType.BlockChance]: 50,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.TowerShield,
    name: 'Tower Shield',
    size: [4, 2],
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [22, 25],
        [BasePropertyType.BlockChance]: 54,
        [BasePropertyType.Durability]: 60,
        [BasePropertyType.RequiredStrength]: 75,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.GothicShield,
    name: 'Gothic Shield',
    size: [4, 2],
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Normal,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [30, 35],
        [BasePropertyType.BlockChance]: 46,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.RequiredStrength]: 60,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Defender,
    name: 'Defender',
    size: [2, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.Buckler,
    imageId: ids.Buckler,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [41, 49],
        [BasePropertyType.BlockChance]: 40,
        [BasePropertyType.Durability]: 68,
        [BasePropertyType.RequiredStrength]: 38,
        [BasePropertyType.RequiredLevel]: 22,
        [BasePropertyType.MaxSockets]: 1,
      },
    },
  },
  {
    id: ids.RoundShield,
    name: 'Round Shield',
    size: [2, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.SmallShield,
    imageId: ids.SmallShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [47, 55],
        [BasePropertyType.BlockChance]: 42,
        [BasePropertyType.Durability]: 64,
        [BasePropertyType.RequiredStrength]: 53,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.Scutum,
    name: 'Scutum',
    size: [3, 2],
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.LargeShield,
    imageId: ids.LargeShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [53, 61],
        [BasePropertyType.BlockChance]: 44,
        [BasePropertyType.Durability]: 64,
        [BasePropertyType.RequiredStrength]: 71,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.DragonShield,
    name: 'Dragon Shield',
    size: [3, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.KiteShield,
    imageId: ids.KiteShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [59, 67],
        [BasePropertyType.BlockChance]: 48,
        [BasePropertyType.Durability]: 76,
        [BasePropertyType.RequiredStrength]: 91,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.BarbedShield,
    name: 'Barbed Shield',
    size: [3, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.SpikedShield,
    imageId: ids.SpikedShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [68, 78],
        [BasePropertyType.BlockChance]: 47,
        [BasePropertyType.Durability]: 55,
        [BasePropertyType.RequiredStrength]: 65,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.GrimShield,
    name: 'Grim Shield',
    size: [3, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Exceptional,
    baseId: ids.BoneShield,
    imageId: ids.BoneShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [50, 150],
        [BasePropertyType.BlockChance]: 50,
        [BasePropertyType.Durability]: 70,
        [BasePropertyType.RequiredStrength]: 58,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.Pavise,
    name: 'Pavise',
    size: [4, 2],
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Exceptional,
    baseId: ids.TowerShield,
    imageId: ids.TowerShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [68, 78],
        [BasePropertyType.BlockChance]: 50,
        [BasePropertyType.Durability]: 72,
        [BasePropertyType.RequiredStrength]: 133,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.AncientShield,
    name: 'Ancient Shield',
    size: [4, 2],
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Exceptional,
    baseId: ids.GothicShield,
    imageId: ids.GothicShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [80, 93],
        [BasePropertyType.BlockChance]: 46,
        [BasePropertyType.Durability]: 80,
        [BasePropertyType.RequiredStrength]: 110,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Heater,
    name: 'Heater',
    size: [2, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.Buckler,
    imageId: ids.Buckler,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [95, 110],
        [BasePropertyType.BlockChance]: 52,
        [BasePropertyType.Durability]: 88,
        [BasePropertyType.RequiredStrength]: 77,
        [BasePropertyType.RequiredLevel]: 43,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.Luna,
    name: 'Luna',
    size: [2, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.SmallShield,
    imageId: ids.SmallShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [108, 123],
        [BasePropertyType.BlockChance]: 50,
        [BasePropertyType.Durability]: 84,
        [BasePropertyType.RequiredStrength]: 100,
        [BasePropertyType.RequiredLevel]: 45,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.Hyperion,
    name: 'Hyperion',
    size: [3, 2],
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.LargeShield,
    imageId: ids.LargeShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [119, 135],
        [BasePropertyType.BlockChance]: 54,
        [BasePropertyType.Durability]: 82,
        [BasePropertyType.RequiredStrength]: 127,
        [BasePropertyType.RequiredLevel]: 48,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Monarch,
    name: 'Monarch',
    size: [3, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.KiteShield,
    imageId: ids.KiteShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [133, 148],
        [BasePropertyType.BlockChance]: 52,
        [BasePropertyType.Durability]: 86,
        [BasePropertyType.RequiredStrength]: 156,
        [BasePropertyType.RequiredLevel]: 54,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.BladeBarrier,
    name: 'Blade Barrier',
    size: [3, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.SpikedShield,
    imageId: ids.SpikedShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [147, 163],
        [BasePropertyType.BlockChance]: 50,
        [BasePropertyType.Durability]: 83,
        [BasePropertyType.RequiredStrength]: 118,
        [BasePropertyType.RequiredLevel]: 51,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.TrollNest,
    name: 'Troll Nest',
    size: [3, 2],
    armorType: ArmorClassType.Light,
    tier: ItemTierType.Elite,
    baseId: ids.BoneShield,
    imageId: ids.BoneShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [158, 173],
        [BasePropertyType.BlockChance]: 50,
        [BasePropertyType.Durability]: 74,
        [BasePropertyType.RequiredStrength]: 106,
        [BasePropertyType.RequiredLevel]: 57,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Aegis,
    name: 'Aegis',
    size: [4, 2],
    armorType: ArmorClassType.Heavy,
    tier: ItemTierType.Elite,
    baseId: ids.TowerShield,
    imageId: ids.TowerShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [145, 161],
        [BasePropertyType.BlockChance]: 54,
        [BasePropertyType.Durability]: 92,
        [BasePropertyType.RequiredStrength]: 219,
        [BasePropertyType.RequiredLevel]: 59,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.Ward,
    name: 'Ward',
    size: [4, 2],
    armorType: ArmorClassType.Medium,
    tier: ItemTierType.Elite,
    baseId: ids.GothicShield,
    imageId: ids.GothicShield,
    properties: {
      base: {
        [BasePropertyType.BaseDefense]: [153, 170],
        [BasePropertyType.BlockChance]: 54,
        [BasePropertyType.Durability]: 100,
        [BasePropertyType.RequiredStrength]: 185,
        [BasePropertyType.RequiredLevel]: 63,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
]);
