import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  PlayerClassType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  playerClass: PlayerClassType.Sorceress,
  class: WeaponClassType.Staff,
  type: ItemType.SorceressOrb,
})([
  {
    id: ids.EagleOrb,
    name: 'Eagle Orb',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 2, max: 5},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.SacredGlobe,
    name: 'Sacred Orb',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 3, max: 8},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.SmokedSphere,
    name: 'Smoked Sphere',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 4, max: 10},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.ClaspedOrb,
    name: 'Clapsed Orb',
    tier: ItemTierType.Normal,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 5, max: 12},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.JaredsStone,
    name: "Jared's Stone",
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 8, max: 18},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.GlowingOrb,
    name: 'Glowing Orb',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.EagleOrb,
    imageId: ids.EagleOrb,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 8, max: 21},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 24,
      },
    },
  },
  {
    id: ids.CrystallineGlobe,
    name: 'Crystalline Globe',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.SacredGlobe,
    imageId: ids.SacredGlobe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 10, max: 26},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 27,
      },
    },
  },
  {
    id: ids.CloudySphere,
    name: 'Cloudy Sphere',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.SmokedSphere,
    imageId: ids.SmokedSphere,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 11, max: 29},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 30,
      },
    },
  },
  {
    id: ids.SparklingBall,
    name: 'Sparkling Ball',
    tier: ItemTierType.Exceptional,
    size: [2, 1],
    baseId: ids.ClaspedOrb,
    imageId: ids.ClaspedOrb,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 13, max: 32},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 34,
      },
    },
  },
  {
    id: ids.SwirlingCrystal,
    name: 'Swirling Crystal',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.JaredsStone,
    imageId: ids.JaredsStone,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 18, max: 42},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 37,
      },
    },
  },
  {
    id: ids.HeavenlyStone,
    name: 'Heavenly Stone',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.EagleOrb,
    imageId: ids.EagleOrb,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 21, max: 46},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 44,
      },
    },
  },
  {
    id: ids.EldritchOrb,
    name: 'Eldritch Orb',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.SacredGlobe,
    imageId: ids.SacredGlobe,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 18, max: 50},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 50,
      },
    },
  },
  {
    id: ids.DemonHeart,
    name: 'Demon Heart',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.SmokedSphere,
    imageId: ids.SmokedSphere,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 23, max: 55},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 56,
      },
    },
  },
  {
    id: ids.VortexOrb,
    name: 'Vortex Orb',
    tier: ItemTierType.Elite,
    size: [2, 1],
    baseId: ids.ClaspedOrb,
    imageId: ids.ClaspedOrb,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 12, max: 66},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 63,
      },
    },
  },
  {
    id: ids.DimensionalShard,
    name: 'Dimensional Shard',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.JaredsStone,
    imageId: ids.JaredsStone,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 30, max: 53},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 66,
      },
    },
  },
]);
