import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Spear,
  size: [4, 2],
  type: ItemType.Spear,
})([
  {
    id: ids.Spear,
    name: 'Spear',
    tier: ItemTierType.Normal,
    qlvl: 5,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 3, max: 15},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Trident,
    name: 'Trident',
    tier: ItemTierType.Normal,
    qlvl: 9,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 9, max: 15},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 38,
        [BasePropertyType.RequiredDexterity]: 24,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.Brandistock,
    name: 'Brandistock',
    tier: ItemTierType.Normal,
    qlvl: 16,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 7, max: 17},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 40,
        [BasePropertyType.RequiredDexterity]: 50,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.Spetum,
    name: 'Spetum',
    tier: ItemTierType.Normal,
    qlvl: 20,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 15, max: 23},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 54,
        [BasePropertyType.RequiredDexterity]: 35,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.Pike,
    name: 'Pike',
    tier: ItemTierType.Normal,
    qlvl: 24,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 14, max: 63},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.RequiredStrength]: 60,
        [BasePropertyType.RequiredDexterity]: 45,
        [BasePropertyType.Durability]: 25,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.WarSpear,
    name: 'War Spear',
    tier: ItemTierType.Exceptional,
    clvl: 21,
    qlvl: 33,
    baseId: ids.Spear,
    imageId: ids.Spear,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 10, max: 37},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 25,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Fuscina,
    name: 'Fuscina',
    tier: ItemTierType.Exceptional,
    clvl: 24,
    qlvl: 36,
    baseId: ids.Trident,
    imageId: ids.Trident,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 19, max: 37},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 77,
        [BasePropertyType.RequiredDexterity]: 25,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.WarFork,
    name: 'War Fork',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 41,
    baseId: ids.Brandistock,
    imageId: ids.Brandistock,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 16, max: 40},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 80,
        [BasePropertyType.RequiredDexterity]: 95,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.Yari,
    name: 'Yari',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 44,
    baseId: ids.Spetum,
    imageId: ids.Spetum,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 29, max: 50},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 101,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.Lance,
    name: 'Lance',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 47,
    baseId: ids.Pike,
    imageId: ids.Pike,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 27, max: 114},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.RequiredStrength]: 110,
        [BasePropertyType.RequiredDexterity]: 88,
        [BasePropertyType.Durability]: 25,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.HyperionSpear,
    name: 'Hyperion Spear',
    tier: ItemTierType.Elite,
    clvl: 43,
    qlvl: 58,
    baseId: ids.Spear,
    imageId: ids.Spear,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 35, max: 119},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 155,
        [BasePropertyType.RequiredDexterity]: 120,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.StygianPike,
    name: 'Stygian Pike',
    tier: ItemTierType.Elite,
    clvl: 49,
    qlvl: 66,
    baseId: ids.Trident,
    imageId: ids.Trident,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 29, max: 114},
        [BasePropertyType.MeleeRange]: 4,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 168,
        [BasePropertyType.RequiredDexterity]: 97,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.Mancatcher,
    name: 'Mancatcher',
    tier: ItemTierType.Elite,
    clvl: 55,
    qlvl: 74,
    baseId: ids.Brandistock,
    imageId: ids.Brandistock,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 42, max: 92},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 132,
        [BasePropertyType.RequiredDexterity]: 134,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.GhostSpear,
    name: 'Ghost Spear',
    tier: ItemTierType.Elite,
    clvl: 62,
    qlvl: 83,
    baseId: ids.Spetum,
    imageId: ids.Spetum,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 18, max: 155},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 122,
        [BasePropertyType.RequiredDexterity]: 163,
        [BasePropertyType.Durability]: 28,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.WarPike,
    name: 'War Pike',
    tier: ItemTierType.Elite,
    clvl: 66,
    qlvl: 85,
    baseId: ids.Pike,
    imageId: ids.Pike,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 33, max: 1778},
        [BasePropertyType.MeleeRange]: 5,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.RequiredStrength]: 165,
        [BasePropertyType.RequiredDexterity]: 106,
        [BasePropertyType.Durability]: 25,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
]);
