import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Staff,
  type: ItemType.Staff,
})([
  {
    id: ids.ShortStaff,
    name: 'Short Staff',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 1, max: 5},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.LongStaff,
    name: 'Long Staff',
    tier: ItemTierType.Normal,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 2, max: 8},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.GnarledStaff,
    name: 'Gnarled Staff',
    tier: ItemTierType.Normal,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 4, max: 12},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.BattleStaff,
    name: 'Battle Staff',
    tier: ItemTierType.Normal,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 6, max: 13},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.WarStaff,
    name: 'War Staff',
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 12, max: 28},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.JoStaff,
    name: 'Jo Staff',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.ShortStaff,
    imageId: ids.ShortStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 6, max: 21},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 18,
      },
    },
  },
  {
    id: ids.Quaterstaff,
    name: 'Quaterstaff',
    tier: ItemTierType.Exceptional,
    size: [4, 1],
    baseId: ids.LongStaff,
    imageId: ids.LongStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 8, max: 26},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.Durability]: 30,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 23,
      },
    },
  },
  {
    id: ids.CedarStaff,
    name: 'Cedar Staff',
    tier: ItemTierType.Exceptional,
    size: [4, 1],
    baseId: ids.GnarledStaff,
    imageId: ids.GnarledStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 11, max: 32},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.GothicStaff,
    name: 'Gothic Staff',
    tier: ItemTierType.Exceptional,
    size: [4, 1],
    baseId: ids.BattleStaff,
    imageId: ids.BattleStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 14, max: 34},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.RuneStaff,
    name: 'Rune Staff',
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.WarStaff,
    imageId: ids.WarStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 24, max: 58},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.WalkingStick,
    name: 'Walking Stick',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.ShortStaff,
    imageId: ids.ShortStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 69, max: 85},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 43,
      },
    },
  },
  {
    id: ids.Stalagmite,
    name: 'Stalagmite',
    tier: ItemTierType.Elite,
    size: [4, 1],
    baseId: ids.LongStaff,
    imageId: ids.LongStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 75, max: 107},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 63,
        [BasePropertyType.RequiredDexterity]: 35,
        [BasePropertyType.Durability]: 39,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 49,
      },
    },
  },
  {
    id: ids.ElderStaff,
    name: 'Elder Staff',
    tier: ItemTierType.Elite,
    size: [4, 1],
    baseId: ids.GnarledStaff,
    imageId: ids.GnarledStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 80, max: 93},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 44,
        [BasePropertyType.RequiredDexterity]: 37,
        [BasePropertyType.Durability]: 35,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 55,
      },
    },
  },
  {
    id: ids.Shillelagh,
    name: 'Shillelagh',
    tier: ItemTierType.Elite,
    size: [4, 1],
    baseId: ids.BattleStaff,
    imageId: ids.BattleStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 65, max: 108},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 52,
        [BasePropertyType.RequiredDexterity]: 27,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 62,
      },
    },
  },
  {
    id: ids.ArchonStaff,
    name: 'Archon Staff',
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.WarStaff,
    imageId: ids.WarStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: {min: 83, max: 99},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 34,
        [BasePropertyType.Durability]: 26,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 66,
      },
    },
  },
]);
