import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Staff,
  type: ItemType.Staff,
})([
  {
    id: ids.ShortStaff,
    name: 'Short Staff',
    tier: ItemTierType.Normal,
    qlvl: 1,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [1, 5],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.LongStaff,
    name: 'Long Staff',
    tier: ItemTierType.Normal,
    qlvl: 8,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [2, 8],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.Durability]: [30],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.GnarledStaff,
    name: 'Gnarled Staff',
    tier: ItemTierType.Normal,
    qlvl: 12,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [4, 12],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.Durability]: [35],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.BattleStaff,
    name: 'Battle Staff',
    tier: ItemTierType.Normal,
    qlvl: 17,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [6, 13],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.Durability]: [40],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.WarStaff,
    name: 'War Staff',
    tier: ItemTierType.Normal,
    qlvl: 24,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [12, 28],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [20],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.JoStaff,
    name: 'Jo Staff',
    tier: ItemTierType.Exceptional,
    clvl: 18,
    qlvl: 30,
    size: [3, 1],
    baseId: ids.ShortStaff,
    imageId: ids.ShortStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [6, 21],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.Quaterstaff,
    name: 'Quaterstaff',
    tier: ItemTierType.Exceptional,
    clvl: 23,
    qlvl: 35,
    size: [4, 1],
    baseId: ids.LongStaff,
    imageId: ids.LongStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [8, 26],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.Durability]: [30],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.CedarStaff,
    name: 'Cedar Staff',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 38,
    size: [4, 1],
    baseId: ids.GnarledStaff,
    imageId: ids.GnarledStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [11, 32],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.Durability]: [35],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.GothicStaff,
    name: 'Gothic Staff',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 42,
    size: [4, 1],
    baseId: ids.BattleStaff,
    imageId: ids.BattleStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [14, 34],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.Durability]: [40],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.RuneStaff,
    name: 'Rune Staff',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 47,
    size: [4, 2],
    baseId: ids.WarStaff,
    imageId: ids.WarStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [24, 58],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [20],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.WalkingStick,
    name: 'Walking Stick',
    tier: ItemTierType.Elite,
    clvl: 43,
    qlvl: 58,
    size: [3, 1],
    baseId: ids.ShortStaff,
    imageId: ids.ShortStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [69, 85],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.MinimumStrength]: [25],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.Stalagmite,
    name: 'Stalagmite',
    tier: ItemTierType.Elite,
    clvl: 49,
    qlvl: 66,
    size: [4, 1],
    baseId: ids.LongStaff,
    imageId: ids.LongStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [75, 107],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [63],
        [BasePropertyType.MinimumDexterity]: [35],
        [BasePropertyType.Durability]: [39],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.ElderStaff,
    name: 'Elder Staff',
    tier: ItemTierType.Elite,
    clvl: 55,
    qlvl: 74,
    size: [4, 1],
    baseId: ids.GnarledStaff,
    imageId: ids.GnarledStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [80, 93],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [44],
        [BasePropertyType.MinimumDexterity]: [37],
        [BasePropertyType.Durability]: [35],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.Shillelagh,
    name: 'Shillelagh',
    tier: ItemTierType.Elite,
    clvl: 62,
    qlvl: 83,
    size: [4, 1],
    baseId: ids.BattleStaff,
    imageId: ids.BattleStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [65, 108],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.MinimumStrength]: [52],
        [BasePropertyType.MinimumDexterity]: [27],
        [BasePropertyType.Durability]: [40],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.ArchonStaff,
    name: 'Archon Staff',
    tier: ItemTierType.Elite,
    clvl: 66,
    qlvl: 85,
    size: [4, 2],
    baseId: ids.WarStaff,
    imageId: ids.WarStaff,
    properties: {
      base: {
        [BasePropertyType.Damage2H]: [83, 99],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.MinimumStrength]: [34],
        [BasePropertyType.Durability]: [26],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
]);
