import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Sword,
  type: ItemType.Sword,
})([
  {
    id: ids.ShortSword,
    name: 'Short Sword',
    tier: ItemTierType.Normal,
    qlvl: 1,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [2, 7],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.Durability]: [24],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.Scimitar,
    name: 'Scimitar',
    tier: ItemTierType.Normal,
    qlvl: 5,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [2, 6],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [-20],
        [BasePropertyType.RequiredDexterity]: [21],
        [BasePropertyType.Durability]: [22],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.Sabre,
    name: 'Sabre',
    tier: ItemTierType.Normal,
    qlvl: 8,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [3, 8],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [25],
        [BasePropertyType.RequiredDexterity]: [25],
        [BasePropertyType.Durability]: [32],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.Falchion,
    name: 'Falchion',
    tier: ItemTierType.Normal,
    qlvl: 11,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [9, 17],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [20],
        [BasePropertyType.RequiredStrength]: [33],
        [BasePropertyType.Durability]: [32],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.CrystalSword,
    name: 'Crystal Sword',
    tier: ItemTierType.Normal,
    qlvl: 11,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [5, 15],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [43],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.BroadSword,
    name: 'Broad Sword',
    tier: ItemTierType.Normal,
    qlvl: 15,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [7, 14],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [48],
        [BasePropertyType.Durability]: [32],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.LongSword,
    name: 'Long Sword',
    tier: ItemTierType.Normal,
    qlvl: 20,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [3, 19],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [55],
        [BasePropertyType.RequiredDexterity]: [39],
        [BasePropertyType.Durability]: [44],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.WarSword,
    name: 'War Sword',
    tier: ItemTierType.Normal,
    qlvl: 27,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [8, 20],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [71],
        [BasePropertyType.RequiredDexterity]: [45],
        [BasePropertyType.Durability]: [44],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.TwoHandedSword,
    name: 'Two-handed Sword',
    tier: ItemTierType.Normal,
    qlvl: 10,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [2, 9],
        [BasePropertyType.Damage2H]: [8, 17],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [35],
        [BasePropertyType.RequiredDexterity]: [27],
        [BasePropertyType.Durability]: [44],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.Claymore,
    name: 'Claymore',
    tier: ItemTierType.Normal,
    qlvl: 17,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [5, 12],
        [BasePropertyType.Damage2H]: [13, 30],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [47],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.GiantSword,
    name: 'Giant Sword',
    tier: ItemTierType.Normal,
    qlvl: 21,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [3, 16],
        [BasePropertyType.Damage2H]: [9, 28],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [56],
        [BasePropertyType.RequiredDexterity]: [34],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.BastardSword,
    name: 'Bastard Sword',
    tier: ItemTierType.Normal,
    qlvl: 24,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [7, 19],
        [BasePropertyType.Damage2H]: [20, 28],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [62],
        [BasePropertyType.Durability]: [40],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.Flamberge,
    name: 'Flamberge',
    tier: ItemTierType.Normal,
    qlvl: 27,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [9, 15],
        [BasePropertyType.Damage2H]: [13, 26],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [70],
        [BasePropertyType.RequiredDexterity]: [49],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.GreatSword,
    name: 'Great Sword',
    tier: ItemTierType.Normal,
    qlvl: 33,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [12, 20],
        [BasePropertyType.Damage2H]: [25, 42],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [100],
        [BasePropertyType.RequiredDexterity]: [60],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.Gladius,
    name: 'Gladius',
    tier: ItemTierType.Exceptional,
    clvl: 18,
    qlvl: 30,
    size: [3, 1],
    baseId: ids.ShortSword,
    imageId: ids.ShortSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [8, 22],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [25],
        [BasePropertyType.Durability]: [24],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.Cutlass,
    name: 'Cutlass',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 43,
    size: [3, 1],
    baseId: ids.Scimitar,
    imageId: ids.Scimitar,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [8, 21],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [-30],
        [BasePropertyType.RequiredStrength]: [25],
        [BasePropertyType.RequiredDexterity]: [52],
        [BasePropertyType.Durability]: [22],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.Shamshir,
    name: 'Shamshir',
    tier: ItemTierType.Exceptional,
    clvl: 23,
    qlvl: 35,
    size: [3, 1],
    baseId: ids.Sabre,
    imageId: ids.Sabre,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [10, 24],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [58],
        [BasePropertyType.RequiredDexterity]: [58],
        [BasePropertyType.Durability]: [32],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.Tulwar,
    name: 'Tulwar',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 37,
    size: [3, 1],
    baseId: ids.Falchion,
    imageId: ids.Falchion,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [16, 35],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [20],
        [BasePropertyType.RequiredStrength]: [70],
        [BasePropertyType.RequiredDexterity]: [42],
        [BasePropertyType.Durability]: [32],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.DimensionalBlade,
    name: 'Dimensional Blade',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 37,
    size: [3, 2],
    baseId: ids.CrystalSword,
    imageId: ids.CrystalSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [13, 35],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [85],
        [BasePropertyType.RequiredDexterity]: [60],
        [BasePropertyType.Durability]: [20],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.BattleSword,
    name: 'Battle Sword',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 40,
    size: [3, 2],
    baseId: ids.BroadSword,
    imageId: ids.BroadSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [16, 34],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [92],
        [BasePropertyType.RequiredDexterity]: [43],
        [BasePropertyType.Durability]: [32],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.RuneSword,
    name: 'Rune Sword',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 44,
    size: [3, 2],
    baseId: ids.LongSword,
    imageId: ids.LongSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [10, 42],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [103],
        [BasePropertyType.RequiredDexterity]: [79],
        [BasePropertyType.Durability]: [44],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.AncientSword,
    name: 'Ancient Sword',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 49,
    size: [3, 1],
    baseId: ids.WarSword,
    imageId: ids.WarSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [18, 43],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [127],
        [BasePropertyType.RequiredDexterity]: [88],
        [BasePropertyType.Durability]: [44],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.Espandon,
    name: 'Espandon',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 37,
    size: [4, 1],
    baseId: ids.TwoHandedSword,
    imageId: ids.TwoHandedSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [8, 26],
        [BasePropertyType.Damage2H]: [18, 40],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [73],
        [BasePropertyType.RequiredDexterity]: [61],
        [BasePropertyType.Durability]: [44],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.DacianFalx,
    name: 'Dacian Falx',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 42,
    size: [4, 1],
    baseId: ids.Claymore,
    imageId: ids.Claymore,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [13, 30],
        [BasePropertyType.Damage2H]: [26, 61],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [91],
        [BasePropertyType.RequiredDexterity]: [20],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.TuskSword,
    name: 'Tusk Sword',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 45,
    size: [4, 1],
    baseId: ids.GiantSword,
    imageId: ids.GiantSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [10, 37],
        [BasePropertyType.Damage2H]: [19, 58],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [104],
        [BasePropertyType.RequiredDexterity]: [71],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.GothicSword,
    name: 'Gothic Sword',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 48,
    size: [4, 1],
    baseId: ids.BastardSword,
    imageId: ids.BastardSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [14, 40],
        [BasePropertyType.Damage2H]: [39, 60],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [113],
        [BasePropertyType.RequiredDexterity]: [20],
        [BasePropertyType.Durability]: [40],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.Zweihander,
    name: 'Zweihander',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 49,
    size: [4, 2],
    baseId: ids.Flamberge,
    imageId: ids.Flamberge,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [19, 35],
        [BasePropertyType.Damage2H]: [29, 54],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [125],
        [BasePropertyType.RequiredDexterity]: [94],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.ExecutionerSword,
    name: 'Executioner Sword',
    tier: ItemTierType.Exceptional,
    clvl: 25,
    qlvl: 54,
    size: [4, 2],
    baseId: ids.GreatSword,
    imageId: ids.GreatSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [24, 40],
        [BasePropertyType.Damage2H]: [47, 80],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [170],
        [BasePropertyType.RequiredDexterity]: [110],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.Falcata,
    name: 'Falcata',
    tier: ItemTierType.Elite,
    clvl: 42,
    qlvl: 56,
    size: [3, 1],
    baseId: ids.ShortSword,
    imageId: ids.ShortSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [31, 59],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [150],
        [BasePropertyType.RequiredDexterity]: [88],
        [BasePropertyType.Durability]: [24],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.Ataghan,
    name: 'Ataghan',
    tier: ItemTierType.Elite,
    clvl: 45,
    qlvl: 61,
    size: [3, 1],
    baseId: ids.Scimitar,
    imageId: ids.Scimitar,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [26, 46],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [-20],
        [BasePropertyType.RequiredStrength]: [135],
        [BasePropertyType.RequiredDexterity]: [95],
        [BasePropertyType.Durability]: [22],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.ElegantBlade,
    name: 'Elegant Blade',
    tier: ItemTierType.Elite,
    clvl: 47,
    qlvl: 63,
    size: [3, 1],
    baseId: ids.Sabre,
    imageId: ids.Sabre,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [33, 45],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [109],
        [BasePropertyType.RequiredDexterity]: [122],
        [BasePropertyType.Durability]: [32],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.HydraEdge,
    name: 'Hydra Edge',
    tier: ItemTierType.Elite,
    clvl: 51,
    qlvl: 69,
    size: [3, 1],
    baseId: ids.Falchion,
    imageId: ids.Falchion,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [28, 68],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [142],
        [BasePropertyType.RequiredDexterity]: [105],
        [BasePropertyType.Durability]: [32],
        [BasePropertyType.MaxSockets]: [2],
      },
    },
  },
  {
    id: ids.PhaseBlade,
    name: 'Phase Blade',
    tier: ItemTierType.Elite,
    clvl: 54,
    qlvl: 73,
    size: [3, 2],
    baseId: ids.CrystalSword,
    imageId: ids.CrystalSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [31, 35],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [-30],
        [BasePropertyType.RequiredStrength]: [25],
        [BasePropertyType.RequiredDexterity]: [136],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
  {
    id: ids.ConquestSword,
    name: 'Conquest Sword',
    tier: ItemTierType.Elite,
    clvl: 58,
    qlvl: 78,
    size: [3, 2],
    baseId: ids.BroadSword,
    imageId: ids.BroadSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [37, 53],
        [BasePropertyType.MeleeRange]: [1],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [142],
        [BasePropertyType.RequiredDexterity]: [112],
        [BasePropertyType.Durability]: [32],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.CrypticSword,
    name: 'Cryptic Sword',
    tier: ItemTierType.Elite,
    clvl: 61,
    qlvl: 82,
    size: [3, 2],
    baseId: ids.LongSword,
    imageId: ids.LongSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [5, 77],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [99],
        [BasePropertyType.RequiredDexterity]: [109],
        [BasePropertyType.Durability]: [44],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.MythicalSword,
    name: 'Mythical Sword',
    tier: ItemTierType.Elite,
    clvl: 66,
    qlvl: 85,
    size: [3, 1],
    baseId: ids.WarSword,
    imageId: ids.WarSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [40, 50],
        [BasePropertyType.MeleeRange]: [2],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [147],
        [BasePropertyType.RequiredDexterity]: [124],
        [BasePropertyType.Durability]: [44],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.LegendSword,
    name: 'Legend Sword',
    tier: ItemTierType.Elite,
    clvl: 44,
    qlvl: 59,
    size: [4, 1],
    baseId: ids.TwoHandedSword,
    imageId: ids.TwoHandedSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [20, 56],
        [BasePropertyType.Damage2H]: [50, 94],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [-15],
        [BasePropertyType.RequiredStrength]: [175],
        [BasePropertyType.RequiredDexterity]: [100],
        [BasePropertyType.Durability]: [44],
        [BasePropertyType.MaxSockets]: [3],
      },
    },
  },
  {
    id: ids.HighlandBlade,
    name: 'Highland Blade',
    tier: ItemTierType.Elite,
    clvl: 49,
    qlvl: 66,
    size: [4, 1],
    baseId: ids.Claymore,
    imageId: ids.Claymore,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [22, 62],
        [BasePropertyType.Damage2H]: [67, 96],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [-5],
        [BasePropertyType.RequiredStrength]: [171],
        [BasePropertyType.RequiredDexterity]: [104],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.BalrogBlade,
    name: 'Balrog Blade',
    tier: ItemTierType.Elite,
    clvl: 53,
    qlvl: 71,
    size: [4, 1],
    baseId: ids.GiantSword,
    imageId: ids.GiantSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [15, 75],
        [BasePropertyType.Damage2H]: [55, 118],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [0],
        [BasePropertyType.RequiredStrength]: [185],
        [BasePropertyType.RequiredDexterity]: [87],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.ChampionSword,
    name: 'Champion Sword',
    tier: ItemTierType.Elite,
    clvl: 57,
    qlvl: 77,
    size: [4, 1],
    baseId: ids.BastardSword,
    imageId: ids.BastardSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [24, 54],
        [BasePropertyType.Damage2H]: [71, 83],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [-10],
        [BasePropertyType.RequiredStrength]: [163],
        [BasePropertyType.RequiredDexterity]: [103],
        [BasePropertyType.Durability]: [40],
        [BasePropertyType.MaxSockets]: [4],
      },
    },
  },
  {
    id: ids.ColossusSword,
    name: 'Colossus Sword',
    tier: ItemTierType.Elite,
    clvl: 80,
    qlvl: 60,
    size: [4, 2],
    baseId: ids.Flamberge,
    imageId: ids.Flamberge,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [26, 70],
        [BasePropertyType.Damage2H]: [61, 121],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [10],
        [BasePropertyType.RequiredStrength]: [182],
        [BasePropertyType.RequiredDexterity]: [95],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [5],
      },
    },
  },
  {
    id: ids.ColossusBlade,
    name: 'Colossus Blade',
    tier: ItemTierType.Elite,
    clvl: 63,
    qlvl: 85,
    size: [4, 2],
    baseId: ids.GreatSword,
    imageId: ids.GreatSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: [25, 65],
        [BasePropertyType.Damage2H]: [58, 115],
        [BasePropertyType.MeleeRange]: [3],
        [BasePropertyType.AttackSpeed]: [5],
        [BasePropertyType.RequiredStrength]: [189],
        [BasePropertyType.RequiredDexterity]: [110],
        [BasePropertyType.Durability]: [50],
        [BasePropertyType.MaxSockets]: [6],
      },
    },
  },
]);
