import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  class: WeaponClassType.Sword,
  type: ItemType.Sword,
})([
  {
    id: ids.ShortSword,
    name: 'Short Sword',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 2, max: 7},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.Scimitar,
    name: 'Scimitar',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 2, max: 6},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredDexterity]: 21,
        [BasePropertyType.Durability]: 22,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.Sabre,
    name: 'Sabre',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 3, max: 8},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 25,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.Falchion,
    name: 'Falchion',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 9, max: 17},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.RequiredStrength]: 33,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
      },
    },
  },
  {
    id: ids.CrystalSword,
    name: 'Crystal Sword',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 5, max: 15},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 43,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.BroadSword,
    name: 'Broad Sword',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 7, max: 14},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 48,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.LongSword,
    name: 'Long Sword',
    tier: ItemTierType.Normal,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 3, max: 19},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 55,
        [BasePropertyType.RequiredDexterity]: 39,
        [BasePropertyType.Durability]: 44,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.WarSword,
    name: 'War Sword',
    tier: ItemTierType.Normal,
    size: [3, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 8, max: 20},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 71,
        [BasePropertyType.RequiredDexterity]: 45,
        [BasePropertyType.Durability]: 44,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.TwoHandedSword,
    name: 'Two-handed Sword',
    tier: ItemTierType.Normal,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 2, max: 9},
        [BasePropertyType.Damage2H]: {min: 8, max: 17},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 35,
        [BasePropertyType.RequiredDexterity]: 27,
        [BasePropertyType.Durability]: 44,
        [BasePropertyType.MaxSockets]: 3,
      },
    },
  },
  {
    id: ids.Claymore,
    name: 'Claymore',
    tier: ItemTierType.Normal,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 5, max: 12},
        [BasePropertyType.Damage2H]: {min: 13, max: 30},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 47,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.GiantSword,
    name: 'Giant Sword',
    tier: ItemTierType.Normal,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 3, max: 16},
        [BasePropertyType.Damage2H]: {min: 9, max: 28},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 56,
        [BasePropertyType.RequiredDexterity]: 34,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.BastardSword,
    name: 'Bastard Sword',
    tier: ItemTierType.Normal,
    size: [4, 1],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 7, max: 19},
        [BasePropertyType.Damage2H]: {min: 20, max: 28},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 62,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 4,
      },
    },
  },
  {
    id: ids.Flamberge,
    name: 'Flamberge',
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 9, max: 15},
        [BasePropertyType.Damage2H]: {min: 13, max: 26},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 70,
        [BasePropertyType.RequiredDexterity]: 49,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 5,
      },
    },
  },
  {
    id: ids.GreatSword,
    name: 'Great Sword',
    tier: ItemTierType.Normal,
    size: [4, 2],
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 12, max: 20},
        [BasePropertyType.Damage2H]: {min: 25, max: 42},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 100,
        [BasePropertyType.RequiredDexterity]: 60,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
      },
    },
  },
  {
    id: ids.Gladius,
    name: 'Gladius',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.ShortSword,
    imageId: ids.ShortSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 8, max: 22},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 18,
      },
    },
  },
  {
    id: ids.Cutlass,
    name: 'Cutlass',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.Scimitar,
    imageId: ids.Scimitar,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 8, max: 21},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -30,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 52,
        [BasePropertyType.Durability]: 22,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Shamshir,
    name: 'Shamshir',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.Sabre,
    imageId: ids.Sabre,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 10, max: 24},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 58,
        [BasePropertyType.RequiredDexterity]: 58,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 23,
      },
    },
  },
  {
    id: ids.Tulwar,
    name: 'Tulwar',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.Falchion,
    imageId: ids.Falchion,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 16, max: 35},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 20,
        [BasePropertyType.RequiredStrength]: 70,
        [BasePropertyType.RequiredDexterity]: 42,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.DimensionalBlade,
    name: 'Dimensional Blade',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.CrystalSword,
    imageId: ids.CrystalSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 13, max: 35},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 85,
        [BasePropertyType.RequiredDexterity]: 60,
        [BasePropertyType.Durability]: 20,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.BattleSword,
    name: 'Battle Sword',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.BroadSword,
    imageId: ids.BroadSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 16, max: 34},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 92,
        [BasePropertyType.RequiredDexterity]: 43,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.RuneSword,
    name: 'Rune Sword',
    tier: ItemTierType.Exceptional,
    size: [3, 2],
    baseId: ids.LongSword,
    imageId: ids.LongSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 10, max: 42},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 103,
        [BasePropertyType.RequiredDexterity]: 79,
        [BasePropertyType.Durability]: 44,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.AncientSword,
    name: 'Ancient Sword',
    tier: ItemTierType.Exceptional,
    size: [3, 1],
    baseId: ids.WarSword,
    imageId: ids.WarSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 18, max: 43},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 127,
        [BasePropertyType.RequiredDexterity]: 88,
        [BasePropertyType.Durability]: 44,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Espandon,
    name: 'Espandon',
    tier: ItemTierType.Exceptional,
    size: [4, 1],
    baseId: ids.TwoHandedSword,
    imageId: ids.TwoHandedSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 8, max: 26},
        [BasePropertyType.Damage2H]: {min: 18, max: 40},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 73,
        [BasePropertyType.RequiredDexterity]: 61,
        [BasePropertyType.Durability]: 44,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.DacianFalx,
    name: 'Dacian Falx',
    tier: ItemTierType.Exceptional,
    size: [4, 1],
    baseId: ids.Claymore,
    imageId: ids.Claymore,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 13, max: 30},
        [BasePropertyType.Damage2H]: {min: 26, max: 61},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 91,
        [BasePropertyType.RequiredDexterity]: 20,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.TuskSword,
    name: 'Tusk Sword',
    tier: ItemTierType.Exceptional,
    size: [4, 1],
    baseId: ids.GiantSword,
    imageId: ids.GiantSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 10, max: 37},
        [BasePropertyType.Damage2H]: {min: 19, max: 58},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 104,
        [BasePropertyType.RequiredDexterity]: 71,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.GothicSword,
    name: 'Gothic Sword',
    tier: ItemTierType.Exceptional,
    size: [4, 1],
    baseId: ids.BastardSword,
    imageId: ids.BastardSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 14, max: 40},
        [BasePropertyType.Damage2H]: {min: 39, max: 60},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 113,
        [BasePropertyType.RequiredDexterity]: 20,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Zweihander,
    name: 'Zweihander',
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.Flamberge,
    imageId: ids.Flamberge,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 19, max: 35},
        [BasePropertyType.Damage2H]: {min: 29, max: 54},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 125,
        [BasePropertyType.RequiredDexterity]: 94,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.ExecutionerSword,
    name: 'Executioner Sword',
    tier: ItemTierType.Exceptional,
    size: [4, 2],
    baseId: ids.GreatSword,
    imageId: ids.GreatSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 24, max: 40},
        [BasePropertyType.Damage2H]: {min: 47, max: 80},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 170,
        [BasePropertyType.RequiredDexterity]: 110,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 25,
      },
    },
  },
  {
    id: ids.Falcata,
    name: 'Falcata',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.ShortSword,
    imageId: ids.ShortSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 31, max: 59},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 150,
        [BasePropertyType.RequiredDexterity]: 88,
        [BasePropertyType.Durability]: 24,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 42,
      },
    },
  },
  {
    id: ids.Ataghan,
    name: 'Ataghan',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.Scimitar,
    imageId: ids.Scimitar,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 26, max: 46},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.RequiredStrength]: 135,
        [BasePropertyType.RequiredDexterity]: 95,
        [BasePropertyType.Durability]: 22,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 45,
      },
    },
  },
  {
    id: ids.ElegantBlade,
    name: 'Elegant Blade',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.Sabre,
    imageId: ids.Sabre,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 33, max: 45},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 109,
        [BasePropertyType.RequiredDexterity]: 122,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 47,
      },
    },
  },
  {
    id: ids.HydraEdge,
    name: 'Hydra Edge',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.Falchion,
    imageId: ids.Falchion,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 28, max: 68},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 142,
        [BasePropertyType.RequiredDexterity]: 105,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 2,
        [BasePropertyType.RequiredLevel]: 51,
      },
    },
  },
  {
    id: ids.PhaseBlade,
    name: 'Phase Blade',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.CrystalSword,
    imageId: ids.CrystalSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 31, max: 35},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -30,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredDexterity]: 136,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 54,
      },
    },
  },
  {
    id: ids.ConquestSword,
    name: 'Conquest Sword',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.BroadSword,
    imageId: ids.BroadSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 37, max: 53},
        [BasePropertyType.MeleeRange]: 1,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 142,
        [BasePropertyType.RequiredDexterity]: 112,
        [BasePropertyType.Durability]: 32,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 58,
      },
    },
  },
  {
    id: ids.CrypticSword,
    name: 'Cryptic Sword',
    tier: ItemTierType.Elite,
    size: [3, 2],
    baseId: ids.LongSword,
    imageId: ids.LongSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 5, max: 77},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 99,
        [BasePropertyType.RequiredDexterity]: 109,
        [BasePropertyType.Durability]: 44,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 61,
      },
    },
  },
  {
    id: ids.MythicalSword,
    name: 'Mythical Sword',
    tier: ItemTierType.Elite,
    size: [3, 1],
    baseId: ids.WarSword,
    imageId: ids.WarSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 40, max: 50},
        [BasePropertyType.MeleeRange]: 2,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 147,
        [BasePropertyType.RequiredDexterity]: 124,
        [BasePropertyType.Durability]: 44,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 66,
      },
    },
  },
  {
    id: ids.LegendSword,
    name: 'Legend Sword',
    tier: ItemTierType.Elite,
    size: [4, 1],
    baseId: ids.TwoHandedSword,
    imageId: ids.TwoHandedSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 20, max: 56},
        [BasePropertyType.Damage2H]: {min: 50, max: 94},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -15,
        [BasePropertyType.RequiredStrength]: 175,
        [BasePropertyType.RequiredDexterity]: 100,
        [BasePropertyType.Durability]: 44,
        [BasePropertyType.MaxSockets]: 3,
        [BasePropertyType.RequiredLevel]: 44,
      },
    },
  },
  {
    id: ids.HighlandBlade,
    name: 'Highland Blade',
    tier: ItemTierType.Elite,
    size: [4, 1],
    baseId: ids.Claymore,
    imageId: ids.Claymore,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 22, max: 62},
        [BasePropertyType.Damage2H]: {min: 67, max: 96},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -5,
        [BasePropertyType.RequiredStrength]: 171,
        [BasePropertyType.RequiredDexterity]: 104,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 49,
      },
    },
  },
  {
    id: ids.BalrogBlade,
    name: 'Balrog Blade',
    tier: ItemTierType.Elite,
    size: [4, 1],
    baseId: ids.GiantSword,
    imageId: ids.GiantSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 15, max: 75},
        [BasePropertyType.Damage2H]: {min: 55, max: 118},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.RequiredStrength]: 185,
        [BasePropertyType.RequiredDexterity]: 87,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 53,
      },
    },
  },
  {
    id: ids.ChampionSword,
    name: 'Champion Sword',
    tier: ItemTierType.Elite,
    size: [4, 1],
    baseId: ids.BastardSword,
    imageId: ids.BastardSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 24, max: 54},
        [BasePropertyType.Damage2H]: {min: 71, max: 83},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.RequiredStrength]: 163,
        [BasePropertyType.RequiredDexterity]: 103,
        [BasePropertyType.Durability]: 40,
        [BasePropertyType.MaxSockets]: 4,
        [BasePropertyType.RequiredLevel]: 57,
      },
    },
  },
  {
    id: ids.ColossusSword,
    name: 'Colossus Sword',
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.Flamberge,
    imageId: ids.Flamberge,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 26, max: 70},
        [BasePropertyType.Damage2H]: {min: 61, max: 121},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.RequiredStrength]: 182,
        [BasePropertyType.RequiredDexterity]: 95,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 5,
        [BasePropertyType.RequiredLevel]: 80,
      },
    },
  },
  {
    id: ids.ColossusBlade,
    name: 'Colossus Blade',
    tier: ItemTierType.Elite,
    size: [4, 2],
    baseId: ids.GreatSword,
    imageId: ids.GreatSword,
    properties: {
      base: {
        [BasePropertyType.Damage1H]: {min: 25, max: 65},
        [BasePropertyType.Damage2H]: {min: 58, max: 115},
        [BasePropertyType.MeleeRange]: 3,
        [BasePropertyType.AttackSpeed]: 5,
        [BasePropertyType.RequiredStrength]: 189,
        [BasePropertyType.RequiredDexterity]: 110,
        [BasePropertyType.Durability]: 50,
        [BasePropertyType.MaxSockets]: 6,
        [BasePropertyType.RequiredLevel]: 63,
      },
    },
  },
]);
