import {
  BasePropertyType,
  ItemTierType,
  ItemType,
  SocketCategoryType,
  WeaponClassType,
} from '../../enums/index.js';
import {normalizeItems} from '../utils/normalize-items.js';
import ids from '../ids/index.js';

export default normalizeItems({
  socketCategory: SocketCategoryType.Weapon,
  type: ItemType.ThrowingWeapon,
})([
  {
    id: ids.ThrowingAxe,
    name: 'Throwing Axe',
    tier: ItemTierType.Normal,
    class: WeaponClassType.Axe,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 8, y: 12},
        [BasePropertyType.Damage1H]: {x: 4, y: 7},
        [BasePropertyType.RequiredDexterity]: 40,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.BalancedAxe,
    name: 'Balanced Axe',
    tier: ItemTierType.Normal,
    class: WeaponClassType.Axe,
    size: [3, 2],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 12, y: 15},
        [BasePropertyType.Damage1H]: {x: 5, y: 10},
        [BasePropertyType.RequiredDexterity]: 57,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.ThrowingKnife,
    name: 'Throwing Knife',
    tier: ItemTierType.Normal,
    class: WeaponClassType.Dagger,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 4, y: 9},
        [BasePropertyType.Damage1H]: {x: 2, y: 3},
        [BasePropertyType.RequiredDexterity]: 21,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.BalancedKnife,
    name: 'Balanced Knife',
    tier: ItemTierType.Normal,
    class: WeaponClassType.Dagger,
    size: [2, 1],
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 6, y: 11},
        [BasePropertyType.Damage1H]: {x: 1, y: 8},
        [BasePropertyType.RequiredDexterity]: 51,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.Francisca,
    name: 'Francisca',
    tier: ItemTierType.Exceptional,
    class: WeaponClassType.Axe,
    size: [2, 1],
    baseId: ids.ThrowingAxe,
    imageId: ids.ThrowingAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 18, y: 33},
        [BasePropertyType.Damage1H]: {x: 11, y: 22},
        [BasePropertyType.RequiredDexterity]: 80,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredLevel]: 22,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.Hurlbat,
    name: 'Balanced Axe',
    tier: ItemTierType.Exceptional,
    class: WeaponClassType.Axe,
    size: [3, 2],
    baseId: ids.BalancedAxe,
    imageId: ids.BalancedAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 24, y: 34},
        [BasePropertyType.Damage1H]: {x: 13, y: 27},
        [BasePropertyType.RequiredDexterity]: 106,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredLevel]: 25,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.BattleDart,
    name: 'Battle Dart',
    tier: ItemTierType.Exceptional,
    class: WeaponClassType.Dagger,
    size: [2, 1],
    baseId: ids.ThrowingKnife,
    imageId: ids.ThrowingKnife,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 11, y: 24},
        [BasePropertyType.Damage1H]: {x: 8, y: 16},
        [BasePropertyType.RequiredDexterity]: 52,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredLevel]: 19,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.WarDart,
    name: 'War Dart',
    tier: ItemTierType.Exceptional,
    class: WeaponClassType.Dagger,
    size: [2, 1],
    baseId: ids.BalancedKnife,
    imageId: ids.BalancedKnife,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 14, y: 27},
        [BasePropertyType.Damage1H]: {x: 6, y: 24},
        [BasePropertyType.RequiredDexterity]: 97,
        [BasePropertyType.RequiredStrength]: 25,
        [BasePropertyType.RequiredLevel]: 22,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.FlyingAxe,
    name: 'FlyingAxe',
    tier: ItemTierType.Elite,
    class: WeaponClassType.Axe,
    size: [2, 1],
    baseId: ids.ThrowingAxe,
    imageId: ids.ThrowingAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 15, y: 66},
        [BasePropertyType.Damage1H]: {x: 17, y: 65},
        [BasePropertyType.RequiredDexterity]: 108,
        [BasePropertyType.RequiredStrength]: 88,
        [BasePropertyType.RequiredLevel]: 42,
        [BasePropertyType.AttackSpeed]: 10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.WingedAxe,
    name: 'Winged Axe',
    tier: ItemTierType.Elite,
    class: WeaponClassType.Axe,
    size: [3, 2],
    baseId: ids.BalancedAxe,
    imageId: ids.BalancedAxe,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 7, y: 60},
        [BasePropertyType.Damage1H]: {x: 11, y: 56},
        [BasePropertyType.RequiredDexterity]: 122,
        [BasePropertyType.RequiredStrength]: 96,
        [BasePropertyType.RequiredLevel]: 60,
        [BasePropertyType.AttackSpeed]: -10,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.FlyingKnife,
    name: 'Flying Knife',
    tier: ItemTierType.Elite,
    class: WeaponClassType.Dagger,
    size: [2, 1],
    baseId: ids.ThrowingKnife,
    imageId: ids.ThrowingKnife,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 23, y: 54},
        [BasePropertyType.Damage1H]: {x: 23, y: 54},
        [BasePropertyType.RequiredDexterity]: 141,
        [BasePropertyType.RequiredStrength]: 48,
        [BasePropertyType.RequiredLevel]: 48,
        [BasePropertyType.AttackSpeed]: 0,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
  {
    id: ids.WingedKnife,
    name: 'Winged Knife',
    tier: ItemTierType.Elite,
    class: WeaponClassType.Dagger,
    size: [2, 1],
    baseId: ids.BalancedKnife,
    imageId: ids.BalancedKnife,
    properties: {
      base: {
        [BasePropertyType.DamageThrow]: {x: 23, y: 39},
        [BasePropertyType.Damage1H]: {x: 27, y: 35},
        [BasePropertyType.RequiredDexterity]: 142,
        [BasePropertyType.RequiredStrength]: 45,
        [BasePropertyType.RequiredLevel]: 57,
        [BasePropertyType.AttackSpeed]: -20,
        [BasePropertyType.MeleeRange]: 1,
      },
    },
  },
]);
