export default {
  StagBow: 'StagBow',
  ReflexBow: 'ReflexBow',
  MaidenSpear: 'MaidenSpear',
  MaidenPike: 'MaidenPike',
  MaidenJavelin: 'MaidenJavelin',
  AshwoodBow: 'AshwoodBow',
  CeremonialBow: 'CeremonialBow',
  CeremonialSpear: 'CeremonialSpear',
  CeremonialPike: 'CeremonialPike',
  CeremonialJavelin: 'CeremonialJavelin',
  MatriarchalBow: 'MatriarchalBow',
  GrandMatronBow: 'GrandMatronBow',
  MatriarchalSpear: 'MatriarchalSpear',
  MatriarchalPike: 'MatriarchalPike',
  MatriarchalJavelin: 'MatriarchalJavelin',
};
