export default {
  Katar: 'Katar',
  WristBlade: 'WristBlade',
  HatchetHands: 'HatchetHands',
  Cestus: 'Cestus',
  Claws: 'Claws',
  BladeTalons: 'BladeTalons',
  ScissorsKatar: 'ScissorsKatar',
  Quhab: 'Quhab',
  WristSpike: 'WristSpike',
  Fascia: 'Fascia',
  HandScythe: 'HandScythe',
  GreaterClaws: 'GreaterClaws',
  GreaterTalons: 'GreaterTalons',
  ScissorsQuhab: 'ScissorsQuhab',
  Suwayyah: 'Suwayyah',
  WristSword: 'WristSword',
  WarFist: 'WarFist',
  BattleCestus: 'BattleCestus',
  FeralClaws: 'FeralClaws',
  RunicTalons: 'RunicTalons',
  ScissorsSuwayyah: 'ScissorsSuwayyah',
};
