export default {
  Sash: 'Sash',
  LightBelt: 'LightBelt',
  Belt: 'Belt',
  HeavyBelt: 'HeavyBelt',
  PlatedBelt: 'PlatedBelt',
  DemonhideSash: 'DemonhideSash',
  SharkskinBelt: 'SharkskinBelt',
  MeshBelt: 'MeshBelt',
  BattleBelt: 'BattleBelt',
  WarBelt: 'WarBelt',
  SpiderwebSash: 'SpiderwebSash',
  VampirefangBelt: 'VampirefangBelt',
  MithrilCoil: 'MithrilCoil',
  TrollBelt: 'TrollBelt',
  ColossusGirdle: 'ColossusGirdle',
};
