export default {
  Boots: 'Boots',
  HeavyBoots: 'HeavyBoots',
  ChainBoots: 'ChainBoots',
  LightPlatedBoots: 'LightPlatedBoots',
  Greaves: 'Greaves',
  DemonhideBoots: 'DemonhideBoots',
  SharkskinBoots: 'SharkskinBoots',
  MeshBoots: 'MeshBoots',
  BattleBoots: 'BattleBoots',
  WarBoots: 'WarBoots',
  WyrmhideBoots: 'WyrmhideBoots',
  ScarabshellBoots: 'ScarabshellBoots',
  BoneweaveBoots: 'BoneweaveBoots',
  MirroredBoots: 'MirroredBoots',
  MyrmidonGreaves: 'MyrmidonGreaves',
};
