export default {
  ShortBow: 'ShortBow',
  HuntersBow: 'HuntersBow',
  LongBow: 'LongBow',
  CompositeBow: 'CompositeBow',
  ShortBattleBow: 'ShortBattleBow',
  LongBattleBow: 'LongBattleBow',
  ShortWarBow: 'ShortWarBow',
  LongWarBow: 'LongWarBow',
  EdgeBow: 'EdgeBow',
  RazorBow: 'RazorBow',
  CedarBow: 'CedarBow',
  DoubleBow: 'DoubleBow',
  ShortSiegeBow: 'ShortSiegeBow',
  LargeSiegeBow: 'LargeSiegeBow',
  RuneBow: 'RuneBow',
  GothicBow: 'GothicBow',
  SpiderBow: 'SpiderBow',
  BladeBow: 'BladeBow',
  ShadowBow: 'ShadowBow',
  GreatBow: 'GreatBow',
  DiamondBow: 'DiamondBow',
  CrusaderBow: 'CrusaderBow',
  WardBow: 'WardBow',
  HydraBow: 'HydraBow',
};
