export default {
  Dagger: 'Dagger',
  Dirk: 'Dirk',
  Kris: 'Kris',
  Blade: 'Blade',
  ThrowingKnife: 'ThrowingKnife',
  BalancedKnife: 'BalancedKnife',
  Poignard: 'Poignard',
  Rondel: 'Rondel',
  Cinquedeas: 'Cinquedeas',
  Stiletto: 'Stiletto',
  BattleDart: 'BattleDart',
  WarDart: 'WarDart',
  BoneKnife: 'BoneKnife',
  MithrilPoint: 'MithrilPoint',
  FangedKnife: 'FangedKnife',
  LegendSpike: 'LegendSpike',
  FlyingKnife: 'FlyingKnife',
  WingedKnife: 'WingedKnife',
};
