export default {
  WolfHead: 'WolfHead',
  HawkHelm: 'HawkHelm',
  Antlers: 'Antlers',
  FalconMask: 'FalconMask',
  SpiritMask: 'SpiritMask',
  AlphaHelm: 'AlphaHelm',
  GriffonHeaddress: 'GriffonHeaddress',
  HuntersGuise: 'HuntersGuise',
  SacredFeathers: 'SacredFeathers',
  TotemicMask: 'TotemicMask',
  BloodSpirit: 'BloodSpirit',
  SunSpirit: 'SunSpirit',
  EarthSpirit: 'EarthSpirit',
  SkySpirit: 'SkySpirit',
  DreamSpirit: 'DreamSpirit',
};
