export default {
  LeatherGloves: 'LeatherGloves',
  HeavyGloves: 'HeavyGloves',
  ChainGloves: 'ChainGloves',
  LightGauntlets: 'LightGauntlets',
  Gauntlets: 'Gauntlets',
  DemonhideGloves: 'DemonhideGloves',
  SharkskinGloves: 'SharkskinGloves',
  HeavyBracers: 'HeavyBracers',
  BattleGauntlets: 'BattleGauntlets',
  WarGauntlets: 'WarGauntlets',
  BrambleMitts: 'BrambleMitts',
  VampireboneGloves: 'VampireboneGloves',
  Vambraces: 'Vambraces',
  CrusaderGauntlets: 'CrusaderGauntlets',
  OgreGauntlets: 'OgreGauntlets',
};
