export default {
  Cap: 'Cap',
  SkullCap: 'SkullCap',
  Helm: 'Helm',
  FullHelm: 'FullHelm',
  Mask: 'Mask',
  BoneHelm: 'BoneHelm',
  GreatHelm: 'GreatHelm',
  Crown: 'Crown',
  WarHat: 'WarHat',
  Sallet: 'Sallet',
  Casque: 'Casque',
  Basinet: 'Basinet',
  DeathMask: 'DeathMask',
  GrimHelm: 'GrimHelm',
  WingedHelm: 'WingedHelm',
  GrandCrown: 'GrandCrown',
  Shako: 'Shako',
  Hydraskull: 'Hydraskull',
  Armet: 'Armet',
  GiantConch: 'GiantConch',
  Demonhead: 'Demonhead',
  BoneVisage: 'BoneVisage',
  SpiredHelm: 'SpiredHelm',
  Corona: 'Corona',
};
