export default {
  Club: 'Club',
  SpikedClub: 'SpikedClub',
  Mace: 'Mace',
  MorningStar: 'MorningStar',
  Flail: 'Flail',
  WarHammer: 'WarHammer',
  Maul: 'Maul',
  GreatMaul: 'GreatMaul',
  Cudgel: 'Cudgel',
  BarbedClub: 'BarbedClub',
  FlangedMace: 'FlangedMace',
  JaggedStar: 'JaggedStar',
  Knout: 'Knout',
  BattleHammer: 'BattleHammer',
  WarClub: 'WarClub',
  MartelDeFer: 'MartelDeFer',
  Truncheon: 'Truncheon',
  TyrantClub: 'TyrantClub',
  ReinforcedMace: 'ReinforcedMace',
  DevilStar: 'DevilStar',
  Scourge: 'Scourge',
  LegendaryMallet: 'LegendaryMallet',
  OgreMaul: 'OgreMaul',
  ThunderMaul: 'ThunderMaul',
};
