export default {
  PreservedHead: 'PreservedHead',
  ZombieHead: 'ZombieHead',
  UnravellerHead: 'UnravellerHead',
  GargoyleHead: 'GargoyleHead',
  DemonHead: 'DemonHead',
  MummifiedTrophy: 'MummifiedTrophy',
  FetishTrophy: 'FetishTrophy',
  SextonTrophy: 'SextonTrophy',
  CantorTrophy: 'CantorTrophy',
  HierophantTrophy: 'HierophantTrophy',
  MinionSkull: 'MinionSkull',
  HellspawnSkull: 'HellspawnSkull',
  OverseerSkull: 'OverseerSkull',
  SuccubusSkull: 'SuccubusSkull',
  BloodlordSkull: 'BloodlordSkull',
};
