export default {
  Bardiche: 'Bardiche',
  Voulge: 'Voulge',
  Scythe: 'Scythe',
  Poleaxe: 'Poleaxe',
  Halberd: 'Halberd',
  WarScythe: 'WarScythe',
  LochaberAxe: 'LochaberAxe',
  Bill: 'Bill',
  BattleScythe: 'BattleScythe',
  Partizan: 'Partizan',
  BecDeCorbin: 'BecDeCorbin',
  GrimScythe: 'GrimScythe',
  OgreAxe: 'OgreAxe',
  ColossusVoulge: 'ColossusVoulge',
  Thresher: 'Thresher',
  CrypticAxe: 'CrypticAxe',
  GreatPoleaxe: 'GreatPoleaxe',
  GiantThresher: 'GiantThresher',
};
