export default {
  AntidotePotion: 'AntidotePotion',
  ChokingGasPotion: 'ChokingGasPotion',
  ExplodingPotion: 'ExplodingPotion',
  FullRejuvenationPotion: 'FullRejuvenationPotion',
  FulminatingPotion: 'FulminatingPotion',
  GreaterHealingPotion: 'GreaterHealingPotion',
  GreaterManaPotion: 'GreaterManaPotion',
  HealingPotion: 'HealingPotion',
  LightHealingPotion: 'LightHealingPotion',
  LightManaPotion: 'LightManaPotion',
  ManaPotion: 'ManaPotion',
  MinorHealingPotion: 'MinorHealingPotion',
  MinorManaPotion: 'MinorManaPotion',
  OilPotion: 'OilPotion',
  RancidGasPotion: 'RancidGasPotion',
  RejuvenationPotion: 'RejuvenationPotion',
  StaminaPotion: 'StaminaPotion',
  StranglingGasPotion: 'StranglingGasPotion',
  SuperHealingPotion: 'SuperHealingPotion',
  SuperManaPotion: 'SuperManaPotion',
  ThawingPotion: 'ThawingPotion',
};
