export default {
  ScrollOfInifuss: 'ScrollOfInifuss',
  WirtsLeg: 'WirtsLeg',
  HoradricMalus: 'HoradricMalus',
  BookOfSkill: 'BookOfSkill',
  HoradricScroll: 'HoradricScroll',
  HoradricCube: 'HoradricCube',
  StaffOfKings: 'StaffOfKings',
  AmuletOfTheViper: 'AmuletOfTheViper',
  HoradricStaff: 'HoradricStaff',
  AJadeFigurine: 'AJadeFigurine',
  TheGoldenBird: 'TheGoldenBird',
  PotionOfLife: 'PotionOfLife',
  TheGidbinn: 'TheGidbinn',
  LamEsensTome: 'LamEsensTome',
  KhalimsEye: 'KhalimsEye',
  KhalimsBrain: 'KhalimsBrain',
  KhalimsHeart: 'KhalimsHeart',
  KhalimsFlail: 'KhalimsFlail',
  KhalimsWill: 'KhalimsWill',
  MephistosSoulstone: 'MephistosSoulstone',
  HellforgeHammer: 'HellforgeHammer',
  MalahsPotion: 'MalahsPotion',
  ScrollOfResistance: 'ScrollOfResistance',
};
