export default {
  AldursRhythm: 'AldursRhythm',
  AldursDeception: 'AldursDeception',
  AldursStonyGaze: 'AldursStonyGaze',
  AldursAdvance: 'AldursAdvance',
  BulKathosSacredCharge: 'BulKathosSacredCharge',
  BulKathosTribalGuardian: 'BulKathosTribalGuardian',
  GrisworldsRedemption: 'GrisworldsRedemption',
  GrisworldsHeart: 'GrisworldsHeart',
  GrisworldsHonor: 'GrisworldsHonor',
  GrisworldsValor: 'GrisworldsValor',
  ImmortalKingsStoneCrusher: 'ImmortalKingsStoneCrusher',
  ImmortalKingsSoulCage: 'ImmortalKingsSoulCage',
  ImmortalKingsWill: 'ImmortalKingsWill',
  ImmortalKingsForge: 'ImmortalKingsForge',
  ImmortalKingsDetail: 'ImmortalKingsDetail',
  ImmortalKingsPillar: 'ImmortalKingsPillar',
};
