export default {
  Buckler: 'Buckler',
  SmallShield: 'SmallShield',
  LargeShield: 'LargeShield',
  KiteShield: 'KiteShield',
  SpikedShield: 'SpikedShield',
  BoneShield: 'BoneShield',
  TowerShield: 'TowerShield',
  GothicShield: 'GothicShield',
  Defender: 'Defender',
  RoundShield: 'RoundShield',
  Scutum: 'Scutum',
  DragonShield: 'DragonShield',
  BarbedShield: 'BarbedShield',
  GrimShield: 'GrimShield',
  Pavise: 'Pavise',
  AnchientShield: 'AnchientShield',
  Heater: 'Heater',
  Luna: 'Luna',
  Hyperion: 'Hyperion',
  Monarch: 'Monarch',
  BladeBarrier: 'BladeBarrier',
  TrollNest: 'TrollNest',
  Aegis: 'Aegis',
  Ward: 'Ward',
};
