export default {
  Spear: 'Spear',
  Trident: 'Trident',
  Brandistock: 'Brandistock',
  Spetum: 'Spetum',
  Pike: 'Pike',
  WarSpear: 'WarSpear',
  Fuscina: 'Fuscina',
  WarFork: 'WarFork',
  Yari: 'Yari',
  Lance: 'Lance',
  HyperionSpear: 'HyperionSpear',
  StygianPike: 'StygianPike',
  Mancatcher: 'Mancatcher',
  GhostSpear: 'GhostSpear',
  WarPike: 'WarPike',
};
