export default {
  // Amulets
  AtmasScarab: 'AtmasScarab',
  CrescentMoon: 'CrescentMoon',
  HighlordsWrath: 'HighlordsWrath',
  MarasKaleidoscope: 'MarasKaleidoscope',
  Metalgrid: 'Metalgrid',
  NokozanRelic: 'NokozanRelic',
  SaracensChance: 'SaracensChance',
  SeraphsHymn: 'SeraphsHymn',
  TheCatsEye: 'TheCatsEye',
  TheEyeOfEtlich: 'TheEyeOfEtlich',
  TheMahimOakCurio: 'TheMahimOakCurio',
  TheRisingSun: 'TheRisingSun',
  // Charms
  Annihilus: 'Annihilus',
  HellfireTorch: 'HellfireTorch',
  GheedsFortune: 'GheedsFortune',
  // Jewels
  RainbowFacetLevelCold: 'RainbowFacetLevelCold',
  RainbowFacetLevelFire: 'RainbowFacetLevelFire',
  RainbowFacetLevelLightning: 'RainbowFacetLevelLightning',
  RainbowFacetLevelPoison: 'RainbowFacetLevelPoison',
  RainbowFacetDeathCold: 'RainbowFacetDeathCold',
  RainbowFacetDeathFire: 'RainbowFacetDeathFire',
  RainbowFacetDeathLightning: 'RainbowFacetDeathLightning',
  RainbowFacetDeathPoison: 'RainbowFacetDeathPoison',
  // Rings
  BulKathosWeddingBand: 'BulKathosWeddingBand',
  CarrionWind: 'CarrionWind',
  DwarfStar: 'DwarfStar',
  ManaldHeal: 'ManaldHeal',
  Nagelring: 'Nagelring',
  NaturesPeace: 'NaturesPeace',
  RavenFrost: 'RavenFrost',
  StoneOfJordan: 'StoneOfJordan',
  WhispProjector: 'WhispProjector',
  // Shields
  LidlessWall: 'LidlessWall',
  WallOfTheEyeless: 'WallOfTheEyeless',
  // Swords
  BladeOfAliBaba: 'BladeOfAliBaba',
  BloodCrescent: 'BloodCrescent',
};
